// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/iwsn-messages.proto

package de.uniluebeck.itm.tr.iwsn.messages;

/**
 * Protobuf type {@code de.uniluebeck.itm.tr.iwsn.messages.AreNodesConnectedRequest}
 */
public  final class AreNodesConnectedRequest extends
    com.google.protobuf.GeneratedMessage
    implements AreNodesConnectedRequestOrBuilder {
  // Use AreNodesConnectedRequest.newBuilder() to construct.
  private AreNodesConnectedRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private AreNodesConnectedRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final AreNodesConnectedRequest defaultInstance;
  public static AreNodesConnectedRequest getDefaultInstance() {
    return defaultInstance;
  }

  public AreNodesConnectedRequest getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private AreNodesConnectedRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              nodeUrns_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            nodeUrns_.add(input.readBytes());
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        nodeUrns_ = new com.google.protobuf.UnmodifiableLazyStringList(nodeUrns_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return de.uniluebeck.itm.tr.iwsn.messages.Messages.internal_static_de_uniluebeck_itm_tr_iwsn_messages_AreNodesConnectedRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return de.uniluebeck.itm.tr.iwsn.messages.Messages.internal_static_de_uniluebeck_itm_tr_iwsn_messages_AreNodesConnectedRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            de.uniluebeck.itm.tr.iwsn.messages.AreNodesConnectedRequest.class, de.uniluebeck.itm.tr.iwsn.messages.AreNodesConnectedRequest.Builder.class);
  }

  public static com.google.protobuf.Parser<AreNodesConnectedRequest> PARSER =
      new com.google.protobuf.AbstractParser<AreNodesConnectedRequest>() {
    public AreNodesConnectedRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AreNodesConnectedRequest(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<AreNodesConnectedRequest> getParserForType() {
    return PARSER;
  }

  // repeated string nodeUrns = 1;
  public static final int NODEURNS_FIELD_NUMBER = 1;
  private com.google.protobuf.LazyStringList nodeUrns_;
  /**
   * <code>repeated string nodeUrns = 1;</code>
   */
  public java.util.List<java.lang.String>
      getNodeUrnsList() {
    return nodeUrns_;
  }
  /**
   * <code>repeated string nodeUrns = 1;</code>
   */
  public int getNodeUrnsCount() {
    return nodeUrns_.size();
  }
  /**
   * <code>repeated string nodeUrns = 1;</code>
   */
  public java.lang.String getNodeUrns(int index) {
    return nodeUrns_.get(index);
  }
  /**
   * <code>repeated string nodeUrns = 1;</code>
   */
  public com.google.protobuf.ByteString
      getNodeUrnsBytes(int index) {
    return nodeUrns_.getByteString(index);
  }

  private void initFields() {
    nodeUrns_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized != -1) return isInitialized == 1;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    for (int i = 0; i < nodeUrns_.size(); i++) {
      output.writeBytes(1, nodeUrns_.getByteString(i));
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < nodeUrns_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeBytesSizeNoTag(nodeUrns_.getByteString(i));
      }
      size += dataSize;
      size += 1 * getNodeUrnsList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static de.uniluebeck.itm.tr.iwsn.messages.AreNodesConnectedRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static de.uniluebeck.itm.tr.iwsn.messages.AreNodesConnectedRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static de.uniluebeck.itm.tr.iwsn.messages.AreNodesConnectedRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static de.uniluebeck.itm.tr.iwsn.messages.AreNodesConnectedRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static de.uniluebeck.itm.tr.iwsn.messages.AreNodesConnectedRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static de.uniluebeck.itm.tr.iwsn.messages.AreNodesConnectedRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static de.uniluebeck.itm.tr.iwsn.messages.AreNodesConnectedRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static de.uniluebeck.itm.tr.iwsn.messages.AreNodesConnectedRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static de.uniluebeck.itm.tr.iwsn.messages.AreNodesConnectedRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static de.uniluebeck.itm.tr.iwsn.messages.AreNodesConnectedRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(de.uniluebeck.itm.tr.iwsn.messages.AreNodesConnectedRequest prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code de.uniluebeck.itm.tr.iwsn.messages.AreNodesConnectedRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder>
     implements de.uniluebeck.itm.tr.iwsn.messages.AreNodesConnectedRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.uniluebeck.itm.tr.iwsn.messages.Messages.internal_static_de_uniluebeck_itm_tr_iwsn_messages_AreNodesConnectedRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.uniluebeck.itm.tr.iwsn.messages.Messages.internal_static_de_uniluebeck_itm_tr_iwsn_messages_AreNodesConnectedRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              de.uniluebeck.itm.tr.iwsn.messages.AreNodesConnectedRequest.class, de.uniluebeck.itm.tr.iwsn.messages.AreNodesConnectedRequest.Builder.class);
    }

    // Construct using de.uniluebeck.itm.tr.iwsn.messages.AreNodesConnectedRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      nodeUrns_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return de.uniluebeck.itm.tr.iwsn.messages.Messages.internal_static_de_uniluebeck_itm_tr_iwsn_messages_AreNodesConnectedRequest_descriptor;
    }

    public de.uniluebeck.itm.tr.iwsn.messages.AreNodesConnectedRequest getDefaultInstanceForType() {
      return de.uniluebeck.itm.tr.iwsn.messages.AreNodesConnectedRequest.getDefaultInstance();
    }

    public de.uniluebeck.itm.tr.iwsn.messages.AreNodesConnectedRequest build() {
      de.uniluebeck.itm.tr.iwsn.messages.AreNodesConnectedRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public de.uniluebeck.itm.tr.iwsn.messages.AreNodesConnectedRequest buildPartial() {
      de.uniluebeck.itm.tr.iwsn.messages.AreNodesConnectedRequest result = new de.uniluebeck.itm.tr.iwsn.messages.AreNodesConnectedRequest(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        nodeUrns_ = new com.google.protobuf.UnmodifiableLazyStringList(
            nodeUrns_);
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.nodeUrns_ = nodeUrns_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof de.uniluebeck.itm.tr.iwsn.messages.AreNodesConnectedRequest) {
        return mergeFrom((de.uniluebeck.itm.tr.iwsn.messages.AreNodesConnectedRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(de.uniluebeck.itm.tr.iwsn.messages.AreNodesConnectedRequest other) {
      if (other == de.uniluebeck.itm.tr.iwsn.messages.AreNodesConnectedRequest.getDefaultInstance()) return this;
      if (!other.nodeUrns_.isEmpty()) {
        if (nodeUrns_.isEmpty()) {
          nodeUrns_ = other.nodeUrns_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureNodeUrnsIsMutable();
          nodeUrns_.addAll(other.nodeUrns_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      de.uniluebeck.itm.tr.iwsn.messages.AreNodesConnectedRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (de.uniluebeck.itm.tr.iwsn.messages.AreNodesConnectedRequest) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    // repeated string nodeUrns = 1;
    private com.google.protobuf.LazyStringList nodeUrns_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureNodeUrnsIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        nodeUrns_ = new com.google.protobuf.LazyStringArrayList(nodeUrns_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string nodeUrns = 1;</code>
     */
    public java.util.List<java.lang.String>
        getNodeUrnsList() {
      return java.util.Collections.unmodifiableList(nodeUrns_);
    }
    /**
     * <code>repeated string nodeUrns = 1;</code>
     */
    public int getNodeUrnsCount() {
      return nodeUrns_.size();
    }
    /**
     * <code>repeated string nodeUrns = 1;</code>
     */
    public java.lang.String getNodeUrns(int index) {
      return nodeUrns_.get(index);
    }
    /**
     * <code>repeated string nodeUrns = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNodeUrnsBytes(int index) {
      return nodeUrns_.getByteString(index);
    }
    /**
     * <code>repeated string nodeUrns = 1;</code>
     */
    public Builder setNodeUrns(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureNodeUrnsIsMutable();
      nodeUrns_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string nodeUrns = 1;</code>
     */
    public Builder addNodeUrns(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureNodeUrnsIsMutable();
      nodeUrns_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string nodeUrns = 1;</code>
     */
    public Builder addAllNodeUrns(
        java.lang.Iterable<java.lang.String> values) {
      ensureNodeUrnsIsMutable();
      super.addAll(values, nodeUrns_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string nodeUrns = 1;</code>
     */
    public Builder clearNodeUrns() {
      nodeUrns_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string nodeUrns = 1;</code>
     */
    public Builder addNodeUrnsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureNodeUrnsIsMutable();
      nodeUrns_.add(value);
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:de.uniluebeck.itm.tr.iwsn.messages.AreNodesConnectedRequest)
  }

  static {
    defaultInstance = new AreNodesConnectedRequest(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:de.uniluebeck.itm.tr.iwsn.messages.AreNodesConnectedRequest)
}

