// Generated by the protocol buffer compiler.  DO NOT EDIT!

package de.uniluebeck.itm.tr.iwsn.messages;

public interface AreNodesAliveRequestOrBuilder
    extends com.google.protobuf.MessageOrBuilder {
  
  // repeated string nodeUrns = 1;
  java.util.List<String> getNodeUrnsList();
  int getNodeUrnsCount();
  String getNodeUrns(int index);
}
