// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/iwsn-messages.proto

package de.uniluebeck.itm.tr.iwsn.messages;

/**
 * Protobuf type {@code de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration}
 */
public  final class ChannelHandlerConfiguration extends
    com.google.protobuf.GeneratedMessage
    implements ChannelHandlerConfigurationOrBuilder {
  // Use ChannelHandlerConfiguration.newBuilder() to construct.
  private ChannelHandlerConfiguration(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private ChannelHandlerConfiguration(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final ChannelHandlerConfiguration defaultInstance;
  public static ChannelHandlerConfiguration getDefaultInstance() {
    return defaultInstance;
  }

  public ChannelHandlerConfiguration getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private ChannelHandlerConfiguration(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            bitField0_ |= 0x00000001;
            name_ = input.readBytes();
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              configuration_ = new java.util.ArrayList<de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePair>();
              mutable_bitField0_ |= 0x00000002;
            }
            configuration_.add(input.readMessage(de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePair.PARSER, extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        configuration_ = java.util.Collections.unmodifiableList(configuration_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return de.uniluebeck.itm.tr.iwsn.messages.Messages.internal_static_de_uniluebeck_itm_tr_iwsn_messages_ChannelHandlerConfiguration_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return de.uniluebeck.itm.tr.iwsn.messages.Messages.internal_static_de_uniluebeck_itm_tr_iwsn_messages_ChannelHandlerConfiguration_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.class, de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.Builder.class);
  }

  public static com.google.protobuf.Parser<ChannelHandlerConfiguration> PARSER =
      new com.google.protobuf.AbstractParser<ChannelHandlerConfiguration>() {
    public ChannelHandlerConfiguration parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ChannelHandlerConfiguration(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<ChannelHandlerConfiguration> getParserForType() {
    return PARSER;
  }

  public interface KeyValuePairOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string key = 1;
    /**
     * <code>required string key = 1;</code>
     */
    boolean hasKey();
    /**
     * <code>required string key = 1;</code>
     */
    java.lang.String getKey();
    /**
     * <code>required string key = 1;</code>
     */
    com.google.protobuf.ByteString
        getKeyBytes();

    // required string value = 2;
    /**
     * <code>required string value = 2;</code>
     */
    boolean hasValue();
    /**
     * <code>required string value = 2;</code>
     */
    java.lang.String getValue();
    /**
     * <code>required string value = 2;</code>
     */
    com.google.protobuf.ByteString
        getValueBytes();
  }
  /**
   * Protobuf type {@code de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePair}
   */
  public static final class KeyValuePair extends
      com.google.protobuf.GeneratedMessage
      implements KeyValuePairOrBuilder {
    // Use KeyValuePair.newBuilder() to construct.
    private KeyValuePair(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private KeyValuePair(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final KeyValuePair defaultInstance;
    public static KeyValuePair getDefaultInstance() {
      return defaultInstance;
    }

    public KeyValuePair getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private KeyValuePair(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              key_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              value_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.uniluebeck.itm.tr.iwsn.messages.Messages.internal_static_de_uniluebeck_itm_tr_iwsn_messages_ChannelHandlerConfiguration_KeyValuePair_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.uniluebeck.itm.tr.iwsn.messages.Messages.internal_static_de_uniluebeck_itm_tr_iwsn_messages_ChannelHandlerConfiguration_KeyValuePair_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePair.class, de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePair.Builder.class);
    }

    public static com.google.protobuf.Parser<KeyValuePair> PARSER =
        new com.google.protobuf.AbstractParser<KeyValuePair>() {
      public KeyValuePair parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new KeyValuePair(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<KeyValuePair> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string key = 1;
    public static final int KEY_FIELD_NUMBER = 1;
    private java.lang.Object key_;
    /**
     * <code>required string key = 1;</code>
     */
    public boolean hasKey() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string key = 1;</code>
     */
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          key_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string key = 1;</code>
     */
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string value = 2;
    public static final int VALUE_FIELD_NUMBER = 2;
    private java.lang.Object value_;
    /**
     * <code>required string value = 2;</code>
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string value = 2;</code>
     */
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          value_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string value = 2;</code>
     */
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      key_ = "";
      value_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasKey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getKeyBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getValueBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getKeyBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getValueBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePair parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePair parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePair parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePair parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePair parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePair parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePair parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePair parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePair parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePair parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePair prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePair}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePairOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return de.uniluebeck.itm.tr.iwsn.messages.Messages.internal_static_de_uniluebeck_itm_tr_iwsn_messages_ChannelHandlerConfiguration_KeyValuePair_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return de.uniluebeck.itm.tr.iwsn.messages.Messages.internal_static_de_uniluebeck_itm_tr_iwsn_messages_ChannelHandlerConfiguration_KeyValuePair_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePair.class, de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePair.Builder.class);
      }

      // Construct using de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePair.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        key_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        value_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return de.uniluebeck.itm.tr.iwsn.messages.Messages.internal_static_de_uniluebeck_itm_tr_iwsn_messages_ChannelHandlerConfiguration_KeyValuePair_descriptor;
      }

      public de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePair getDefaultInstanceForType() {
        return de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePair.getDefaultInstance();
      }

      public de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePair build() {
        de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePair result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePair buildPartial() {
        de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePair result = new de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePair(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.key_ = key_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.value_ = value_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePair) {
          return mergeFrom((de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePair)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePair other) {
        if (other == de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePair.getDefaultInstance()) return this;
        if (other.hasKey()) {
          bitField0_ |= 0x00000001;
          key_ = other.key_;
          onChanged();
        }
        if (other.hasValue()) {
          bitField0_ |= 0x00000002;
          value_ = other.value_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasKey()) {
          
          return false;
        }
        if (!hasValue()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePair parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePair) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string key = 1;
      private java.lang.Object key_ = "";
      /**
       * <code>required string key = 1;</code>
       */
      public boolean hasKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string key = 1;</code>
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          key_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string key = 1;</code>
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string key = 1;</code>
       */
      public Builder setKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string key = 1;</code>
       */
      public Builder clearKey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      /**
       * <code>required string key = 1;</code>
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
        return this;
      }

      // required string value = 2;
      private java.lang.Object value_ = "";
      /**
       * <code>required string value = 2;</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string value = 2;</code>
       */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          value_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string value = 2;</code>
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string value = 2;</code>
       */
      public Builder setValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string value = 2;</code>
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000002);
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      /**
       * <code>required string value = 2;</code>
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        value_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePair)
    }

    static {
      defaultInstance = new KeyValuePair(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePair)
  }

  private int bitField0_;
  // required string name = 1;
  public static final int NAME_FIELD_NUMBER = 1;
  private java.lang.Object name_;
  /**
   * <code>required string name = 1;</code>
   */
  public boolean hasName() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>required string name = 1;</code>
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        name_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string name = 1;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // repeated .de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePair configuration = 2;
  public static final int CONFIGURATION_FIELD_NUMBER = 2;
  private java.util.List<de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePair> configuration_;
  /**
   * <code>repeated .de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePair configuration = 2;</code>
   */
  public java.util.List<de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePair> getConfigurationList() {
    return configuration_;
  }
  /**
   * <code>repeated .de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePair configuration = 2;</code>
   */
  public java.util.List<? extends de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePairOrBuilder> 
      getConfigurationOrBuilderList() {
    return configuration_;
  }
  /**
   * <code>repeated .de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePair configuration = 2;</code>
   */
  public int getConfigurationCount() {
    return configuration_.size();
  }
  /**
   * <code>repeated .de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePair configuration = 2;</code>
   */
  public de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePair getConfiguration(int index) {
    return configuration_.get(index);
  }
  /**
   * <code>repeated .de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePair configuration = 2;</code>
   */
  public de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePairOrBuilder getConfigurationOrBuilder(
      int index) {
    return configuration_.get(index);
  }

  private void initFields() {
    name_ = "";
    configuration_ = java.util.Collections.emptyList();
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized != -1) return isInitialized == 1;

    if (!hasName()) {
      memoizedIsInitialized = 0;
      return false;
    }
    for (int i = 0; i < getConfigurationCount(); i++) {
      if (!getConfiguration(i).isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeBytes(1, getNameBytes());
    }
    for (int i = 0; i < configuration_.size(); i++) {
      output.writeMessage(2, configuration_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, getNameBytes());
    }
    for (int i = 0; i < configuration_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, configuration_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder>
     implements de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfigurationOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.uniluebeck.itm.tr.iwsn.messages.Messages.internal_static_de_uniluebeck_itm_tr_iwsn_messages_ChannelHandlerConfiguration_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.uniluebeck.itm.tr.iwsn.messages.Messages.internal_static_de_uniluebeck_itm_tr_iwsn_messages_ChannelHandlerConfiguration_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.class, de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.Builder.class);
    }

    // Construct using de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getConfigurationFieldBuilder();
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      name_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      if (configurationBuilder_ == null) {
        configuration_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        configurationBuilder_.clear();
      }
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return de.uniluebeck.itm.tr.iwsn.messages.Messages.internal_static_de_uniluebeck_itm_tr_iwsn_messages_ChannelHandlerConfiguration_descriptor;
    }

    public de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration getDefaultInstanceForType() {
      return de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.getDefaultInstance();
    }

    public de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration build() {
      de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration buildPartial() {
      de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration result = new de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.name_ = name_;
      if (configurationBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          configuration_ = java.util.Collections.unmodifiableList(configuration_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.configuration_ = configuration_;
      } else {
        result.configuration_ = configurationBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration) {
        return mergeFrom((de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration other) {
      if (other == de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.getDefaultInstance()) return this;
      if (other.hasName()) {
        bitField0_ |= 0x00000001;
        name_ = other.name_;
        onChanged();
      }
      if (configurationBuilder_ == null) {
        if (!other.configuration_.isEmpty()) {
          if (configuration_.isEmpty()) {
            configuration_ = other.configuration_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureConfigurationIsMutable();
            configuration_.addAll(other.configuration_);
          }
          onChanged();
        }
      } else {
        if (!other.configuration_.isEmpty()) {
          if (configurationBuilder_.isEmpty()) {
            configurationBuilder_.dispose();
            configurationBuilder_ = null;
            configuration_ = other.configuration_;
            bitField0_ = (bitField0_ & ~0x00000002);
            configurationBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getConfigurationFieldBuilder() : null;
          } else {
            configurationBuilder_.addAllMessages(other.configuration_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      if (!hasName()) {
        
        return false;
      }
      for (int i = 0; i < getConfigurationCount(); i++) {
        if (!getConfiguration(i).isInitialized()) {
          
          return false;
        }
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    // required string name = 1;
    private java.lang.Object name_ = "";
    /**
     * <code>required string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string name = 1;</code>
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string name = 1;</code>
     */
    public Builder clearName() {
      bitField0_ = (bitField0_ & ~0x00000001);
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>required string name = 1;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      name_ = value;
      onChanged();
      return this;
    }

    // repeated .de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePair configuration = 2;
    private java.util.List<de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePair> configuration_ =
      java.util.Collections.emptyList();
    private void ensureConfigurationIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        configuration_ = new java.util.ArrayList<de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePair>(configuration_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePair, de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePair.Builder, de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePairOrBuilder> configurationBuilder_;

    /**
     * <code>repeated .de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePair configuration = 2;</code>
     */
    public java.util.List<de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePair> getConfigurationList() {
      if (configurationBuilder_ == null) {
        return java.util.Collections.unmodifiableList(configuration_);
      } else {
        return configurationBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePair configuration = 2;</code>
     */
    public int getConfigurationCount() {
      if (configurationBuilder_ == null) {
        return configuration_.size();
      } else {
        return configurationBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePair configuration = 2;</code>
     */
    public de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePair getConfiguration(int index) {
      if (configurationBuilder_ == null) {
        return configuration_.get(index);
      } else {
        return configurationBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePair configuration = 2;</code>
     */
    public Builder setConfiguration(
        int index, de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePair value) {
      if (configurationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureConfigurationIsMutable();
        configuration_.set(index, value);
        onChanged();
      } else {
        configurationBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePair configuration = 2;</code>
     */
    public Builder setConfiguration(
        int index, de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePair.Builder builderForValue) {
      if (configurationBuilder_ == null) {
        ensureConfigurationIsMutable();
        configuration_.set(index, builderForValue.build());
        onChanged();
      } else {
        configurationBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePair configuration = 2;</code>
     */
    public Builder addConfiguration(de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePair value) {
      if (configurationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureConfigurationIsMutable();
        configuration_.add(value);
        onChanged();
      } else {
        configurationBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePair configuration = 2;</code>
     */
    public Builder addConfiguration(
        int index, de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePair value) {
      if (configurationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureConfigurationIsMutable();
        configuration_.add(index, value);
        onChanged();
      } else {
        configurationBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePair configuration = 2;</code>
     */
    public Builder addConfiguration(
        de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePair.Builder builderForValue) {
      if (configurationBuilder_ == null) {
        ensureConfigurationIsMutable();
        configuration_.add(builderForValue.build());
        onChanged();
      } else {
        configurationBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePair configuration = 2;</code>
     */
    public Builder addConfiguration(
        int index, de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePair.Builder builderForValue) {
      if (configurationBuilder_ == null) {
        ensureConfigurationIsMutable();
        configuration_.add(index, builderForValue.build());
        onChanged();
      } else {
        configurationBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePair configuration = 2;</code>
     */
    public Builder addAllConfiguration(
        java.lang.Iterable<? extends de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePair> values) {
      if (configurationBuilder_ == null) {
        ensureConfigurationIsMutable();
        super.addAll(values, configuration_);
        onChanged();
      } else {
        configurationBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePair configuration = 2;</code>
     */
    public Builder clearConfiguration() {
      if (configurationBuilder_ == null) {
        configuration_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        configurationBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePair configuration = 2;</code>
     */
    public Builder removeConfiguration(int index) {
      if (configurationBuilder_ == null) {
        ensureConfigurationIsMutable();
        configuration_.remove(index);
        onChanged();
      } else {
        configurationBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePair configuration = 2;</code>
     */
    public de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePair.Builder getConfigurationBuilder(
        int index) {
      return getConfigurationFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePair configuration = 2;</code>
     */
    public de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePairOrBuilder getConfigurationOrBuilder(
        int index) {
      if (configurationBuilder_ == null) {
        return configuration_.get(index);  } else {
        return configurationBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePair configuration = 2;</code>
     */
    public java.util.List<? extends de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePairOrBuilder> 
         getConfigurationOrBuilderList() {
      if (configurationBuilder_ != null) {
        return configurationBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(configuration_);
      }
    }
    /**
     * <code>repeated .de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePair configuration = 2;</code>
     */
    public de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePair.Builder addConfigurationBuilder() {
      return getConfigurationFieldBuilder().addBuilder(
          de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePair.getDefaultInstance());
    }
    /**
     * <code>repeated .de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePair configuration = 2;</code>
     */
    public de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePair.Builder addConfigurationBuilder(
        int index) {
      return getConfigurationFieldBuilder().addBuilder(
          index, de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePair.getDefaultInstance());
    }
    /**
     * <code>repeated .de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePair configuration = 2;</code>
     */
    public java.util.List<de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePair.Builder> 
         getConfigurationBuilderList() {
      return getConfigurationFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePair, de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePair.Builder, de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePairOrBuilder> 
        getConfigurationFieldBuilder() {
      if (configurationBuilder_ == null) {
        configurationBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePair, de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePair.Builder, de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.KeyValuePairOrBuilder>(
                configuration_,
                ((bitField0_ & 0x00000002) == 0x00000002),
                getParentForChildren(),
                isClean());
        configuration_ = null;
      }
      return configurationBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration)
  }

  static {
    defaultInstance = new ChannelHandlerConfiguration(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration)
}

