// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/iwsn-messages.proto

package de.uniluebeck.itm.tr.iwsn.messages;

public interface DisableVirtualLinksRequestOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // repeated .de.uniluebeck.itm.tr.iwsn.messages.Link links = 1;
  /**
   * <code>repeated .de.uniluebeck.itm.tr.iwsn.messages.Link links = 1;</code>
   */
  java.util.List<de.uniluebeck.itm.tr.iwsn.messages.Link> 
      getLinksList();
  /**
   * <code>repeated .de.uniluebeck.itm.tr.iwsn.messages.Link links = 1;</code>
   */
  de.uniluebeck.itm.tr.iwsn.messages.Link getLinks(int index);
  /**
   * <code>repeated .de.uniluebeck.itm.tr.iwsn.messages.Link links = 1;</code>
   */
  int getLinksCount();
  /**
   * <code>repeated .de.uniluebeck.itm.tr.iwsn.messages.Link links = 1;</code>
   */
  java.util.List<? extends de.uniluebeck.itm.tr.iwsn.messages.LinkOrBuilder> 
      getLinksOrBuilderList();
  /**
   * <code>repeated .de.uniluebeck.itm.tr.iwsn.messages.Link links = 1;</code>
   */
  de.uniluebeck.itm.tr.iwsn.messages.LinkOrBuilder getLinksOrBuilder(
      int index);
}
