// Generated by the protocol buffer compiler.  DO NOT EDIT!

package de.uniluebeck.itm.tr.iwsn.messages;

public interface ExternalPluginMessageOrBuilder
    extends com.google.protobuf.MessageOrBuilder {
  
  // required .de.uniluebeck.itm.tr.iwsn.messages.ExternalPluginMessage.Type type = 1;
  boolean hasType();
  de.uniluebeck.itm.tr.iwsn.messages.ExternalPluginMessage.Type getType();
  
  // optional .de.uniluebeck.itm.tr.iwsn.messages.InternalMessage internal_message = 101;
  boolean hasInternalMessage();
  de.uniluebeck.itm.tr.iwsn.messages.InternalMessage getInternalMessage();
  de.uniluebeck.itm.tr.iwsn.messages.InternalMessageOrBuilder getInternalMessageOrBuilder();
  
  // optional .de.uniluebeck.itm.tr.iwsn.messages.Message iwsn_message = 102;
  boolean hasIwsnMessage();
  de.uniluebeck.itm.tr.iwsn.messages.Message getIwsnMessage();
  de.uniluebeck.itm.tr.iwsn.messages.MessageOrBuilder getIwsnMessageOrBuilder();
}
