// Generated by the protocol buffer compiler.  DO NOT EDIT!

package de.uniluebeck.itm.tr.iwsn.messages;

public interface GetChannelPipelinesResponseOrBuilder
    extends com.google.protobuf.MessageOrBuilder {
  
  // required .de.uniluebeck.itm.tr.iwsn.messages.Header header = 1;
  boolean hasHeader();
  de.uniluebeck.itm.tr.iwsn.messages.Header getHeader();
  de.uniluebeck.itm.tr.iwsn.messages.HeaderOrBuilder getHeaderOrBuilder();
  
  // repeated .de.uniluebeck.itm.tr.iwsn.messages.GetChannelPipelinesResponse.GetChannelPipelineResponse pipelines = 2;
  java.util.List<de.uniluebeck.itm.tr.iwsn.messages.GetChannelPipelinesResponse.GetChannelPipelineResponse> 
      getPipelinesList();
  de.uniluebeck.itm.tr.iwsn.messages.GetChannelPipelinesResponse.GetChannelPipelineResponse getPipelines(int index);
  int getPipelinesCount();
  java.util.List<? extends de.uniluebeck.itm.tr.iwsn.messages.GetChannelPipelinesResponse.GetChannelPipelineResponseOrBuilder> 
      getPipelinesOrBuilderList();
  de.uniluebeck.itm.tr.iwsn.messages.GetChannelPipelinesResponse.GetChannelPipelineResponseOrBuilder getPipelinesOrBuilder(
      int index);
}
