// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/internal-messages.proto

package de.uniluebeck.itm.tr.iwsn.messages;

public final class InternalMessages {
  private InternalMessages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_de_uniluebeck_itm_tr_iwsn_messages_ReservationEvent_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_de_uniluebeck_itm_tr_iwsn_messages_ReservationEvent_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_de_uniluebeck_itm_tr_iwsn_messages_ReservationEvent_SecretReservationKey_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_de_uniluebeck_itm_tr_iwsn_messages_ReservationEvent_SecretReservationKey_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_de_uniluebeck_itm_tr_iwsn_messages_InternalMessage_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_de_uniluebeck_itm_tr_iwsn_messages_InternalMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n*src/main/resources/internal-messages.p" +
      "roto\022\"de.uniluebeck.itm.tr.iwsn.messages" +
      "\"\232\003\n\020ReservationEvent\022G\n\004type\030\001 \002(\01629.de" +
      ".uniluebeck.itm.tr.iwsn.messages.Reserva" +
      "tionEvent.Type\022h\n\025secretReservationKeys\030" +
      "\002 \003(\0132I.de.uniluebeck.itm.tr.iwsn.messag" +
      "es.ReservationEvent.SecretReservationKey" +
      "\022\020\n\010nodeUrns\030\003 \003(\t\022\026\n\016interval_start\030\004 \002" +
      "(\t\022\024\n\014interval_end\030\005 \002(\t\032L\n\024SecretReserv" +
      "ationKey\022\025\n\rnodeUrnPrefix\030\001 \002(\t\022\020\n\010usern",
      "ame\030\002 \002(\t\022\013\n\003key\030\003 \002(\t\"E\n\004Type\022\013\n\007STARTE" +
      "D\020\001\022\t\n\005ENDED\020\002\022\n\n\006OPENED\020\003\022\n\n\006CLOSED\020\004\022\r" +
      "\n\tFINALIZED\020\005\"\310\001\n\017InternalMessage\022F\n\004typ" +
      "e\030\001 \002(\01628.de.uniluebeck.itm.tr.iwsn.mess" +
      "ages.InternalMessage.Type\022N\n\020reservation" +
      "Event\030e \001(\01324.de.uniluebeck.itm.tr.iwsn." +
      "messages.ReservationEvent\"\035\n\004Type\022\025\n\021RES" +
      "ERVATION_EVENT\020\001B\024B\020InternalMessagesP\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_de_uniluebeck_itm_tr_iwsn_messages_ReservationEvent_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_de_uniluebeck_itm_tr_iwsn_messages_ReservationEvent_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_de_uniluebeck_itm_tr_iwsn_messages_ReservationEvent_descriptor,
              new java.lang.String[] { "Type", "SecretReservationKeys", "NodeUrns", "IntervalStart", "IntervalEnd", });
          internal_static_de_uniluebeck_itm_tr_iwsn_messages_ReservationEvent_SecretReservationKey_descriptor =
            internal_static_de_uniluebeck_itm_tr_iwsn_messages_ReservationEvent_descriptor.getNestedTypes().get(0);
          internal_static_de_uniluebeck_itm_tr_iwsn_messages_ReservationEvent_SecretReservationKey_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_de_uniluebeck_itm_tr_iwsn_messages_ReservationEvent_SecretReservationKey_descriptor,
              new java.lang.String[] { "NodeUrnPrefix", "Username", "Key", });
          internal_static_de_uniluebeck_itm_tr_iwsn_messages_InternalMessage_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_de_uniluebeck_itm_tr_iwsn_messages_InternalMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_de_uniluebeck_itm_tr_iwsn_messages_InternalMessage_descriptor,
              new java.lang.String[] { "Type", "ReservationEvent", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
