// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/iwsn-messages.proto

package de.uniluebeck.itm.tr.iwsn.messages;

public interface LinkOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // required string sourceNodeUrn = 1;
  /**
   * <code>required string sourceNodeUrn = 1;</code>
   */
  boolean hasSourceNodeUrn();
  /**
   * <code>required string sourceNodeUrn = 1;</code>
   */
  java.lang.String getSourceNodeUrn();
  /**
   * <code>required string sourceNodeUrn = 1;</code>
   */
  com.google.protobuf.ByteString
      getSourceNodeUrnBytes();

  // required string targetNodeUrn = 2;
  /**
   * <code>required string targetNodeUrn = 2;</code>
   */
  boolean hasTargetNodeUrn();
  /**
   * <code>required string targetNodeUrn = 2;</code>
   */
  java.lang.String getTargetNodeUrn();
  /**
   * <code>required string targetNodeUrn = 2;</code>
   */
  com.google.protobuf.ByteString
      getTargetNodeUrnBytes();
}
