// Generated by the protocol buffer compiler.  DO NOT EDIT!

package de.uniluebeck.itm.tr.iwsn.messages;

public  final class Message extends
    com.google.protobuf.GeneratedMessage {
  // Use Message.newBuilder() to construct.
  private Message() {
    initFields();
  }
  private Message(boolean noInit) {}
  
  private static final Message defaultInstance;
  public static Message getDefaultInstance() {
    return defaultInstance;
  }
  
  public Message getDefaultInstanceForType() {
    return defaultInstance;
  }
  
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return de.uniluebeck.itm.tr.iwsn.messages.Messages.internal_static_de_uniluebeck_itm_tr_iwsn_messages_Message_descriptor;
  }
  
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return de.uniluebeck.itm.tr.iwsn.messages.Messages.internal_static_de_uniluebeck_itm_tr_iwsn_messages_Message_fieldAccessorTable;
  }
  
  public enum Type
      implements com.google.protobuf.ProtocolMessageEnum {
    REQUEST(0, 1),
    PROGRESS(1, 2),
    RESPONSE(2, 3),
    EVENT(3, 4),
    EVENT_ACK(4, 5),
    ;
    
    
    public final int getNumber() { return value; }
    
    public static Type valueOf(int value) {
      switch (value) {
        case 1: return REQUEST;
        case 2: return PROGRESS;
        case 3: return RESPONSE;
        case 4: return EVENT;
        case 5: return EVENT_ACK;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<Type>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<Type>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Type>() {
            public Type findValueByNumber(int number) {
              return Type.valueOf(number)
    ;        }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return de.uniluebeck.itm.tr.iwsn.messages.Message.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final Type[] VALUES = {
      REQUEST, PROGRESS, RESPONSE, EVENT, EVENT_ACK, 
    };
    public static Type valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    private final int index;
    private final int value;
    private Type(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    static {
      de.uniluebeck.itm.tr.iwsn.messages.Messages.getDescriptor();
    }
    
    // @@protoc_insertion_point(enum_scope:de.uniluebeck.itm.tr.iwsn.messages.Message.Type)
  }
  
  // required .de.uniluebeck.itm.tr.iwsn.messages.Message.Type type = 1;
  public static final int TYPE_FIELD_NUMBER = 1;
  private boolean hasType;
  private de.uniluebeck.itm.tr.iwsn.messages.Message.Type type_;
  public boolean hasType() { return hasType; }
  public de.uniluebeck.itm.tr.iwsn.messages.Message.Type getType() { return type_; }
  
  // optional .de.uniluebeck.itm.tr.iwsn.messages.Request request = 101;
  public static final int REQUEST_FIELD_NUMBER = 101;
  private boolean hasRequest;
  private de.uniluebeck.itm.tr.iwsn.messages.Request request_;
  public boolean hasRequest() { return hasRequest; }
  public de.uniluebeck.itm.tr.iwsn.messages.Request getRequest() { return request_; }
  
  // optional .de.uniluebeck.itm.tr.iwsn.messages.SingleNodeProgress progress = 102;
  public static final int PROGRESS_FIELD_NUMBER = 102;
  private boolean hasProgress;
  private de.uniluebeck.itm.tr.iwsn.messages.SingleNodeProgress progress_;
  public boolean hasProgress() { return hasProgress; }
  public de.uniluebeck.itm.tr.iwsn.messages.SingleNodeProgress getProgress() { return progress_; }
  
  // optional .de.uniluebeck.itm.tr.iwsn.messages.SingleNodeResponse response = 103;
  public static final int RESPONSE_FIELD_NUMBER = 103;
  private boolean hasResponse;
  private de.uniluebeck.itm.tr.iwsn.messages.SingleNodeResponse response_;
  public boolean hasResponse() { return hasResponse; }
  public de.uniluebeck.itm.tr.iwsn.messages.SingleNodeResponse getResponse() { return response_; }
  
  // optional .de.uniluebeck.itm.tr.iwsn.messages.Event event = 104;
  public static final int EVENT_FIELD_NUMBER = 104;
  private boolean hasEvent;
  private de.uniluebeck.itm.tr.iwsn.messages.Event event_;
  public boolean hasEvent() { return hasEvent; }
  public de.uniluebeck.itm.tr.iwsn.messages.Event getEvent() { return event_; }
  
  // optional .de.uniluebeck.itm.tr.iwsn.messages.EventAck eventAck = 105;
  public static final int EVENTACK_FIELD_NUMBER = 105;
  private boolean hasEventAck;
  private de.uniluebeck.itm.tr.iwsn.messages.EventAck eventAck_;
  public boolean hasEventAck() { return hasEventAck; }
  public de.uniluebeck.itm.tr.iwsn.messages.EventAck getEventAck() { return eventAck_; }
  
  private void initFields() {
    type_ = de.uniluebeck.itm.tr.iwsn.messages.Message.Type.REQUEST;
    request_ = de.uniluebeck.itm.tr.iwsn.messages.Request.getDefaultInstance();
    progress_ = de.uniluebeck.itm.tr.iwsn.messages.SingleNodeProgress.getDefaultInstance();
    response_ = de.uniluebeck.itm.tr.iwsn.messages.SingleNodeResponse.getDefaultInstance();
    event_ = de.uniluebeck.itm.tr.iwsn.messages.Event.getDefaultInstance();
    eventAck_ = de.uniluebeck.itm.tr.iwsn.messages.EventAck.getDefaultInstance();
  }
  public final boolean isInitialized() {
    if (!hasType) return false;
    if (hasRequest()) {
      if (!getRequest().isInitialized()) return false;
    }
    if (hasProgress()) {
      if (!getProgress().isInitialized()) return false;
    }
    if (hasResponse()) {
      if (!getResponse().isInitialized()) return false;
    }
    if (hasEvent()) {
      if (!getEvent().isInitialized()) return false;
    }
    if (hasEventAck()) {
      if (!getEventAck().isInitialized()) return false;
    }
    return true;
  }
  
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (hasType()) {
      output.writeEnum(1, getType().getNumber());
    }
    if (hasRequest()) {
      output.writeMessage(101, getRequest());
    }
    if (hasProgress()) {
      output.writeMessage(102, getProgress());
    }
    if (hasResponse()) {
      output.writeMessage(103, getResponse());
    }
    if (hasEvent()) {
      output.writeMessage(104, getEvent());
    }
    if (hasEventAck()) {
      output.writeMessage(105, getEventAck());
    }
    getUnknownFields().writeTo(output);
  }
  
  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;
  
    size = 0;
    if (hasType()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, getType().getNumber());
    }
    if (hasRequest()) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(101, getRequest());
    }
    if (hasProgress()) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(102, getProgress());
    }
    if (hasResponse()) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(103, getResponse());
    }
    if (hasEvent()) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(104, getEvent());
    }
    if (hasEventAck()) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(105, getEventAck());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }
  
  public static de.uniluebeck.itm.tr.iwsn.messages.Message parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return newBuilder().mergeFrom(data).buildParsed();
  }
  public static de.uniluebeck.itm.tr.iwsn.messages.Message parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return newBuilder().mergeFrom(data, extensionRegistry)
             .buildParsed();
  }
  public static de.uniluebeck.itm.tr.iwsn.messages.Message parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return newBuilder().mergeFrom(data).buildParsed();
  }
  public static de.uniluebeck.itm.tr.iwsn.messages.Message parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return newBuilder().mergeFrom(data, extensionRegistry)
             .buildParsed();
  }
  public static de.uniluebeck.itm.tr.iwsn.messages.Message parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return newBuilder().mergeFrom(input).buildParsed();
  }
  public static de.uniluebeck.itm.tr.iwsn.messages.Message parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return newBuilder().mergeFrom(input, extensionRegistry)
             .buildParsed();
  }
  public static de.uniluebeck.itm.tr.iwsn.messages.Message parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    Builder builder = newBuilder();
    if (builder.mergeDelimitedFrom(input)) {
      return builder.buildParsed();
    } else {
      return null;
    }
  }
  public static de.uniluebeck.itm.tr.iwsn.messages.Message parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    Builder builder = newBuilder();
    if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
      return builder.buildParsed();
    } else {
      return null;
    }
  }
  public static de.uniluebeck.itm.tr.iwsn.messages.Message parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return newBuilder().mergeFrom(input).buildParsed();
  }
  public static de.uniluebeck.itm.tr.iwsn.messages.Message parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return newBuilder().mergeFrom(input, extensionRegistry)
             .buildParsed();
  }
  
  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(de.uniluebeck.itm.tr.iwsn.messages.Message prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }
  
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> {
    private de.uniluebeck.itm.tr.iwsn.messages.Message result;
    
    // Construct using de.uniluebeck.itm.tr.iwsn.messages.Message.newBuilder()
    private Builder() {}
    
    private static Builder create() {
      Builder builder = new Builder();
      builder.result = new de.uniluebeck.itm.tr.iwsn.messages.Message();
      return builder;
    }
    
    protected de.uniluebeck.itm.tr.iwsn.messages.Message internalGetResult() {
      return result;
    }
    
    public Builder clear() {
      if (result == null) {
        throw new IllegalStateException(
          "Cannot call clear() after build().");
      }
      result = new de.uniluebeck.itm.tr.iwsn.messages.Message();
      return this;
    }
    
    public Builder clone() {
      return create().mergeFrom(result);
    }
    
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return de.uniluebeck.itm.tr.iwsn.messages.Message.getDescriptor();
    }
    
    public de.uniluebeck.itm.tr.iwsn.messages.Message getDefaultInstanceForType() {
      return de.uniluebeck.itm.tr.iwsn.messages.Message.getDefaultInstance();
    }
    
    public boolean isInitialized() {
      return result.isInitialized();
    }
    public de.uniluebeck.itm.tr.iwsn.messages.Message build() {
      if (result != null && !isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return buildPartial();
    }
    
    private de.uniluebeck.itm.tr.iwsn.messages.Message buildParsed()
        throws com.google.protobuf.InvalidProtocolBufferException {
      if (!isInitialized()) {
        throw newUninitializedMessageException(
          result).asInvalidProtocolBufferException();
      }
      return buildPartial();
    }
    
    public de.uniluebeck.itm.tr.iwsn.messages.Message buildPartial() {
      if (result == null) {
        throw new IllegalStateException(
          "build() has already been called on this Builder.");
      }
      de.uniluebeck.itm.tr.iwsn.messages.Message returnMe = result;
      result = null;
      return returnMe;
    }
    
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof de.uniluebeck.itm.tr.iwsn.messages.Message) {
        return mergeFrom((de.uniluebeck.itm.tr.iwsn.messages.Message)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }
    
    public Builder mergeFrom(de.uniluebeck.itm.tr.iwsn.messages.Message other) {
      if (other == de.uniluebeck.itm.tr.iwsn.messages.Message.getDefaultInstance()) return this;
      if (other.hasType()) {
        setType(other.getType());
      }
      if (other.hasRequest()) {
        mergeRequest(other.getRequest());
      }
      if (other.hasProgress()) {
        mergeProgress(other.getProgress());
      }
      if (other.hasResponse()) {
        mergeResponse(other.getResponse());
      }
      if (other.hasEvent()) {
        mergeEvent(other.getEvent());
      }
      if (other.hasEventAck()) {
        mergeEventAck(other.getEventAck());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }
    
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder(
          this.getUnknownFields());
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            this.setUnknownFields(unknownFields.build());
            return this;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              this.setUnknownFields(unknownFields.build());
              return this;
            }
            break;
          }
          case 8: {
            int rawValue = input.readEnum();
            de.uniluebeck.itm.tr.iwsn.messages.Message.Type value = de.uniluebeck.itm.tr.iwsn.messages.Message.Type.valueOf(rawValue);
            if (value == null) {
              unknownFields.mergeVarintField(1, rawValue);
            } else {
              setType(value);
            }
            break;
          }
          case 810: {
            de.uniluebeck.itm.tr.iwsn.messages.Request.Builder subBuilder = de.uniluebeck.itm.tr.iwsn.messages.Request.newBuilder();
            if (hasRequest()) {
              subBuilder.mergeFrom(getRequest());
            }
            input.readMessage(subBuilder, extensionRegistry);
            setRequest(subBuilder.buildPartial());
            break;
          }
          case 818: {
            de.uniluebeck.itm.tr.iwsn.messages.SingleNodeProgress.Builder subBuilder = de.uniluebeck.itm.tr.iwsn.messages.SingleNodeProgress.newBuilder();
            if (hasProgress()) {
              subBuilder.mergeFrom(getProgress());
            }
            input.readMessage(subBuilder, extensionRegistry);
            setProgress(subBuilder.buildPartial());
            break;
          }
          case 826: {
            de.uniluebeck.itm.tr.iwsn.messages.SingleNodeResponse.Builder subBuilder = de.uniluebeck.itm.tr.iwsn.messages.SingleNodeResponse.newBuilder();
            if (hasResponse()) {
              subBuilder.mergeFrom(getResponse());
            }
            input.readMessage(subBuilder, extensionRegistry);
            setResponse(subBuilder.buildPartial());
            break;
          }
          case 834: {
            de.uniluebeck.itm.tr.iwsn.messages.Event.Builder subBuilder = de.uniluebeck.itm.tr.iwsn.messages.Event.newBuilder();
            if (hasEvent()) {
              subBuilder.mergeFrom(getEvent());
            }
            input.readMessage(subBuilder, extensionRegistry);
            setEvent(subBuilder.buildPartial());
            break;
          }
          case 842: {
            de.uniluebeck.itm.tr.iwsn.messages.EventAck.Builder subBuilder = de.uniluebeck.itm.tr.iwsn.messages.EventAck.newBuilder();
            if (hasEventAck()) {
              subBuilder.mergeFrom(getEventAck());
            }
            input.readMessage(subBuilder, extensionRegistry);
            setEventAck(subBuilder.buildPartial());
            break;
          }
        }
      }
    }
    
    
    // required .de.uniluebeck.itm.tr.iwsn.messages.Message.Type type = 1;
    public boolean hasType() {
      return result.hasType();
    }
    public de.uniluebeck.itm.tr.iwsn.messages.Message.Type getType() {
      return result.getType();
    }
    public Builder setType(de.uniluebeck.itm.tr.iwsn.messages.Message.Type value) {
      if (value == null) {
        throw new NullPointerException();
      }
      result.hasType = true;
      result.type_ = value;
      return this;
    }
    public Builder clearType() {
      result.hasType = false;
      result.type_ = de.uniluebeck.itm.tr.iwsn.messages.Message.Type.REQUEST;
      return this;
    }
    
    // optional .de.uniluebeck.itm.tr.iwsn.messages.Request request = 101;
    public boolean hasRequest() {
      return result.hasRequest();
    }
    public de.uniluebeck.itm.tr.iwsn.messages.Request getRequest() {
      return result.getRequest();
    }
    public Builder setRequest(de.uniluebeck.itm.tr.iwsn.messages.Request value) {
      if (value == null) {
        throw new NullPointerException();
      }
      result.hasRequest = true;
      result.request_ = value;
      return this;
    }
    public Builder setRequest(de.uniluebeck.itm.tr.iwsn.messages.Request.Builder builderForValue) {
      result.hasRequest = true;
      result.request_ = builderForValue.build();
      return this;
    }
    public Builder mergeRequest(de.uniluebeck.itm.tr.iwsn.messages.Request value) {
      if (result.hasRequest() &&
          result.request_ != de.uniluebeck.itm.tr.iwsn.messages.Request.getDefaultInstance()) {
        result.request_ =
          de.uniluebeck.itm.tr.iwsn.messages.Request.newBuilder(result.request_).mergeFrom(value).buildPartial();
      } else {
        result.request_ = value;
      }
      result.hasRequest = true;
      return this;
    }
    public Builder clearRequest() {
      result.hasRequest = false;
      result.request_ = de.uniluebeck.itm.tr.iwsn.messages.Request.getDefaultInstance();
      return this;
    }
    
    // optional .de.uniluebeck.itm.tr.iwsn.messages.SingleNodeProgress progress = 102;
    public boolean hasProgress() {
      return result.hasProgress();
    }
    public de.uniluebeck.itm.tr.iwsn.messages.SingleNodeProgress getProgress() {
      return result.getProgress();
    }
    public Builder setProgress(de.uniluebeck.itm.tr.iwsn.messages.SingleNodeProgress value) {
      if (value == null) {
        throw new NullPointerException();
      }
      result.hasProgress = true;
      result.progress_ = value;
      return this;
    }
    public Builder setProgress(de.uniluebeck.itm.tr.iwsn.messages.SingleNodeProgress.Builder builderForValue) {
      result.hasProgress = true;
      result.progress_ = builderForValue.build();
      return this;
    }
    public Builder mergeProgress(de.uniluebeck.itm.tr.iwsn.messages.SingleNodeProgress value) {
      if (result.hasProgress() &&
          result.progress_ != de.uniluebeck.itm.tr.iwsn.messages.SingleNodeProgress.getDefaultInstance()) {
        result.progress_ =
          de.uniluebeck.itm.tr.iwsn.messages.SingleNodeProgress.newBuilder(result.progress_).mergeFrom(value).buildPartial();
      } else {
        result.progress_ = value;
      }
      result.hasProgress = true;
      return this;
    }
    public Builder clearProgress() {
      result.hasProgress = false;
      result.progress_ = de.uniluebeck.itm.tr.iwsn.messages.SingleNodeProgress.getDefaultInstance();
      return this;
    }
    
    // optional .de.uniluebeck.itm.tr.iwsn.messages.SingleNodeResponse response = 103;
    public boolean hasResponse() {
      return result.hasResponse();
    }
    public de.uniluebeck.itm.tr.iwsn.messages.SingleNodeResponse getResponse() {
      return result.getResponse();
    }
    public Builder setResponse(de.uniluebeck.itm.tr.iwsn.messages.SingleNodeResponse value) {
      if (value == null) {
        throw new NullPointerException();
      }
      result.hasResponse = true;
      result.response_ = value;
      return this;
    }
    public Builder setResponse(de.uniluebeck.itm.tr.iwsn.messages.SingleNodeResponse.Builder builderForValue) {
      result.hasResponse = true;
      result.response_ = builderForValue.build();
      return this;
    }
    public Builder mergeResponse(de.uniluebeck.itm.tr.iwsn.messages.SingleNodeResponse value) {
      if (result.hasResponse() &&
          result.response_ != de.uniluebeck.itm.tr.iwsn.messages.SingleNodeResponse.getDefaultInstance()) {
        result.response_ =
          de.uniluebeck.itm.tr.iwsn.messages.SingleNodeResponse.newBuilder(result.response_).mergeFrom(value).buildPartial();
      } else {
        result.response_ = value;
      }
      result.hasResponse = true;
      return this;
    }
    public Builder clearResponse() {
      result.hasResponse = false;
      result.response_ = de.uniluebeck.itm.tr.iwsn.messages.SingleNodeResponse.getDefaultInstance();
      return this;
    }
    
    // optional .de.uniluebeck.itm.tr.iwsn.messages.Event event = 104;
    public boolean hasEvent() {
      return result.hasEvent();
    }
    public de.uniluebeck.itm.tr.iwsn.messages.Event getEvent() {
      return result.getEvent();
    }
    public Builder setEvent(de.uniluebeck.itm.tr.iwsn.messages.Event value) {
      if (value == null) {
        throw new NullPointerException();
      }
      result.hasEvent = true;
      result.event_ = value;
      return this;
    }
    public Builder setEvent(de.uniluebeck.itm.tr.iwsn.messages.Event.Builder builderForValue) {
      result.hasEvent = true;
      result.event_ = builderForValue.build();
      return this;
    }
    public Builder mergeEvent(de.uniluebeck.itm.tr.iwsn.messages.Event value) {
      if (result.hasEvent() &&
          result.event_ != de.uniluebeck.itm.tr.iwsn.messages.Event.getDefaultInstance()) {
        result.event_ =
          de.uniluebeck.itm.tr.iwsn.messages.Event.newBuilder(result.event_).mergeFrom(value).buildPartial();
      } else {
        result.event_ = value;
      }
      result.hasEvent = true;
      return this;
    }
    public Builder clearEvent() {
      result.hasEvent = false;
      result.event_ = de.uniluebeck.itm.tr.iwsn.messages.Event.getDefaultInstance();
      return this;
    }
    
    // optional .de.uniluebeck.itm.tr.iwsn.messages.EventAck eventAck = 105;
    public boolean hasEventAck() {
      return result.hasEventAck();
    }
    public de.uniluebeck.itm.tr.iwsn.messages.EventAck getEventAck() {
      return result.getEventAck();
    }
    public Builder setEventAck(de.uniluebeck.itm.tr.iwsn.messages.EventAck value) {
      if (value == null) {
        throw new NullPointerException();
      }
      result.hasEventAck = true;
      result.eventAck_ = value;
      return this;
    }
    public Builder setEventAck(de.uniluebeck.itm.tr.iwsn.messages.EventAck.Builder builderForValue) {
      result.hasEventAck = true;
      result.eventAck_ = builderForValue.build();
      return this;
    }
    public Builder mergeEventAck(de.uniluebeck.itm.tr.iwsn.messages.EventAck value) {
      if (result.hasEventAck() &&
          result.eventAck_ != de.uniluebeck.itm.tr.iwsn.messages.EventAck.getDefaultInstance()) {
        result.eventAck_ =
          de.uniluebeck.itm.tr.iwsn.messages.EventAck.newBuilder(result.eventAck_).mergeFrom(value).buildPartial();
      } else {
        result.eventAck_ = value;
      }
      result.hasEventAck = true;
      return this;
    }
    public Builder clearEventAck() {
      result.hasEventAck = false;
      result.eventAck_ = de.uniluebeck.itm.tr.iwsn.messages.EventAck.getDefaultInstance();
      return this;
    }
    
    // @@protoc_insertion_point(builder_scope:de.uniluebeck.itm.tr.iwsn.messages.Message)
  }
  
  static {
    defaultInstance = new Message(true);
    de.uniluebeck.itm.tr.iwsn.messages.Messages.internalForceInit();
    defaultInstance.initFields();
  }
  
  // @@protoc_insertion_point(class_scope:de.uniluebeck.itm.tr.iwsn.messages.Message)
}

