// Generated by the protocol buffer compiler.  DO NOT EDIT!

package de.uniluebeck.itm.tr.iwsn.messages;

public interface MessageOrBuilder
    extends com.google.protobuf.MessageOrBuilder {
  
  // required .de.uniluebeck.itm.tr.iwsn.messages.Message.Type type = 1;
  boolean hasType();
  de.uniluebeck.itm.tr.iwsn.messages.Message.Type getType();
  
  // optional .de.uniluebeck.itm.tr.iwsn.messages.Request request = 101;
  boolean hasRequest();
  de.uniluebeck.itm.tr.iwsn.messages.Request getRequest();
  de.uniluebeck.itm.tr.iwsn.messages.RequestOrBuilder getRequestOrBuilder();
  
  // optional .de.uniluebeck.itm.tr.iwsn.messages.SingleNodeProgress progress = 102;
  boolean hasProgress();
  de.uniluebeck.itm.tr.iwsn.messages.SingleNodeProgress getProgress();
  de.uniluebeck.itm.tr.iwsn.messages.SingleNodeProgressOrBuilder getProgressOrBuilder();
  
  // optional .de.uniluebeck.itm.tr.iwsn.messages.SingleNodeResponse response = 103;
  boolean hasResponse();
  de.uniluebeck.itm.tr.iwsn.messages.SingleNodeResponse getResponse();
  de.uniluebeck.itm.tr.iwsn.messages.SingleNodeResponseOrBuilder getResponseOrBuilder();
  
  // optional .de.uniluebeck.itm.tr.iwsn.messages.Event event = 104;
  boolean hasEvent();
  de.uniluebeck.itm.tr.iwsn.messages.Event getEvent();
  de.uniluebeck.itm.tr.iwsn.messages.EventOrBuilder getEventOrBuilder();
  
  // optional .de.uniluebeck.itm.tr.iwsn.messages.EventAck eventAck = 105;
  boolean hasEventAck();
  de.uniluebeck.itm.tr.iwsn.messages.EventAck getEventAck();
  de.uniluebeck.itm.tr.iwsn.messages.EventAckOrBuilder getEventAckOrBuilder();
}
