// Generated by the protocol buffer compiler.  DO NOT EDIT!

package de.uniluebeck.itm.tr.iwsn.messages;

public interface ProgressOrBuilder
    extends com.google.protobuf.MessageOrBuilder {
  
  // required .de.uniluebeck.itm.tr.iwsn.messages.Header header = 1;
  boolean hasHeader();
  de.uniluebeck.itm.tr.iwsn.messages.Header getHeader();
  de.uniluebeck.itm.tr.iwsn.messages.HeaderOrBuilder getHeaderOrBuilder();
  
  // required uint32 progressInPercent = 2;
  boolean hasProgressInPercent();
  int getProgressInPercent();
}
