// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/iwsn-messages.proto

package de.uniluebeck.itm.tr.iwsn.messages;

public interface SendDownstreamMessagesRequestOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // repeated string targetNodeUrns = 1;
  /**
   * <code>repeated string targetNodeUrns = 1;</code>
   */
  java.util.List<java.lang.String>
  getTargetNodeUrnsList();
  /**
   * <code>repeated string targetNodeUrns = 1;</code>
   */
  int getTargetNodeUrnsCount();
  /**
   * <code>repeated string targetNodeUrns = 1;</code>
   */
  java.lang.String getTargetNodeUrns(int index);
  /**
   * <code>repeated string targetNodeUrns = 1;</code>
   */
  com.google.protobuf.ByteString
      getTargetNodeUrnsBytes(int index);

  // required bytes messageBytes = 2;
  /**
   * <code>required bytes messageBytes = 2;</code>
   */
  boolean hasMessageBytes();
  /**
   * <code>required bytes messageBytes = 2;</code>
   */
  com.google.protobuf.ByteString getMessageBytes();
}
