// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/iwsn-messages.proto

package de.uniluebeck.itm.tr.iwsn.messages;

/**
 * Protobuf type {@code de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessagesRequest}
 */
public  final class SendDownstreamMessagesRequest extends
    com.google.protobuf.GeneratedMessage
    implements SendDownstreamMessagesRequestOrBuilder {
  // Use SendDownstreamMessagesRequest.newBuilder() to construct.
  private SendDownstreamMessagesRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private SendDownstreamMessagesRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final SendDownstreamMessagesRequest defaultInstance;
  public static SendDownstreamMessagesRequest getDefaultInstance() {
    return defaultInstance;
  }

  public SendDownstreamMessagesRequest getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private SendDownstreamMessagesRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              targetNodeUrns_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            targetNodeUrns_.add(input.readBytes());
            break;
          }
          case 18: {
            bitField0_ |= 0x00000001;
            messageBytes_ = input.readBytes();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        targetNodeUrns_ = new com.google.protobuf.UnmodifiableLazyStringList(targetNodeUrns_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return de.uniluebeck.itm.tr.iwsn.messages.Messages.internal_static_de_uniluebeck_itm_tr_iwsn_messages_SendDownstreamMessagesRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return de.uniluebeck.itm.tr.iwsn.messages.Messages.internal_static_de_uniluebeck_itm_tr_iwsn_messages_SendDownstreamMessagesRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessagesRequest.class, de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessagesRequest.Builder.class);
  }

  public static com.google.protobuf.Parser<SendDownstreamMessagesRequest> PARSER =
      new com.google.protobuf.AbstractParser<SendDownstreamMessagesRequest>() {
    public SendDownstreamMessagesRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SendDownstreamMessagesRequest(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<SendDownstreamMessagesRequest> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  // repeated string targetNodeUrns = 1;
  public static final int TARGETNODEURNS_FIELD_NUMBER = 1;
  private com.google.protobuf.LazyStringList targetNodeUrns_;
  /**
   * <code>repeated string targetNodeUrns = 1;</code>
   */
  public java.util.List<java.lang.String>
      getTargetNodeUrnsList() {
    return targetNodeUrns_;
  }
  /**
   * <code>repeated string targetNodeUrns = 1;</code>
   */
  public int getTargetNodeUrnsCount() {
    return targetNodeUrns_.size();
  }
  /**
   * <code>repeated string targetNodeUrns = 1;</code>
   */
  public java.lang.String getTargetNodeUrns(int index) {
    return targetNodeUrns_.get(index);
  }
  /**
   * <code>repeated string targetNodeUrns = 1;</code>
   */
  public com.google.protobuf.ByteString
      getTargetNodeUrnsBytes(int index) {
    return targetNodeUrns_.getByteString(index);
  }

  // required bytes messageBytes = 2;
  public static final int MESSAGEBYTES_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString messageBytes_;
  /**
   * <code>required bytes messageBytes = 2;</code>
   */
  public boolean hasMessageBytes() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>required bytes messageBytes = 2;</code>
   */
  public com.google.protobuf.ByteString getMessageBytes() {
    return messageBytes_;
  }

  private void initFields() {
    targetNodeUrns_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    messageBytes_ = com.google.protobuf.ByteString.EMPTY;
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized != -1) return isInitialized == 1;

    if (!hasMessageBytes()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    for (int i = 0; i < targetNodeUrns_.size(); i++) {
      output.writeBytes(1, targetNodeUrns_.getByteString(i));
    }
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeBytes(2, messageBytes_);
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < targetNodeUrns_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeBytesSizeNoTag(targetNodeUrns_.getByteString(i));
      }
      size += dataSize;
      size += 1 * getTargetNodeUrnsList().size();
    }
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, messageBytes_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessagesRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessagesRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessagesRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessagesRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessagesRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessagesRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessagesRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessagesRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessagesRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessagesRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessagesRequest prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessagesRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder>
     implements de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessagesRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.uniluebeck.itm.tr.iwsn.messages.Messages.internal_static_de_uniluebeck_itm_tr_iwsn_messages_SendDownstreamMessagesRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.uniluebeck.itm.tr.iwsn.messages.Messages.internal_static_de_uniluebeck_itm_tr_iwsn_messages_SendDownstreamMessagesRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessagesRequest.class, de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessagesRequest.Builder.class);
    }

    // Construct using de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessagesRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      targetNodeUrns_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      messageBytes_ = com.google.protobuf.ByteString.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return de.uniluebeck.itm.tr.iwsn.messages.Messages.internal_static_de_uniluebeck_itm_tr_iwsn_messages_SendDownstreamMessagesRequest_descriptor;
    }

    public de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessagesRequest getDefaultInstanceForType() {
      return de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessagesRequest.getDefaultInstance();
    }

    public de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessagesRequest build() {
      de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessagesRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessagesRequest buildPartial() {
      de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessagesRequest result = new de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessagesRequest(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        targetNodeUrns_ = new com.google.protobuf.UnmodifiableLazyStringList(
            targetNodeUrns_);
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.targetNodeUrns_ = targetNodeUrns_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000001;
      }
      result.messageBytes_ = messageBytes_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessagesRequest) {
        return mergeFrom((de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessagesRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessagesRequest other) {
      if (other == de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessagesRequest.getDefaultInstance()) return this;
      if (!other.targetNodeUrns_.isEmpty()) {
        if (targetNodeUrns_.isEmpty()) {
          targetNodeUrns_ = other.targetNodeUrns_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureTargetNodeUrnsIsMutable();
          targetNodeUrns_.addAll(other.targetNodeUrns_);
        }
        onChanged();
      }
      if (other.hasMessageBytes()) {
        setMessageBytes(other.getMessageBytes());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      if (!hasMessageBytes()) {
        
        return false;
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessagesRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessagesRequest) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    // repeated string targetNodeUrns = 1;
    private com.google.protobuf.LazyStringList targetNodeUrns_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureTargetNodeUrnsIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        targetNodeUrns_ = new com.google.protobuf.LazyStringArrayList(targetNodeUrns_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string targetNodeUrns = 1;</code>
     */
    public java.util.List<java.lang.String>
        getTargetNodeUrnsList() {
      return java.util.Collections.unmodifiableList(targetNodeUrns_);
    }
    /**
     * <code>repeated string targetNodeUrns = 1;</code>
     */
    public int getTargetNodeUrnsCount() {
      return targetNodeUrns_.size();
    }
    /**
     * <code>repeated string targetNodeUrns = 1;</code>
     */
    public java.lang.String getTargetNodeUrns(int index) {
      return targetNodeUrns_.get(index);
    }
    /**
     * <code>repeated string targetNodeUrns = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTargetNodeUrnsBytes(int index) {
      return targetNodeUrns_.getByteString(index);
    }
    /**
     * <code>repeated string targetNodeUrns = 1;</code>
     */
    public Builder setTargetNodeUrns(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureTargetNodeUrnsIsMutable();
      targetNodeUrns_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string targetNodeUrns = 1;</code>
     */
    public Builder addTargetNodeUrns(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureTargetNodeUrnsIsMutable();
      targetNodeUrns_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string targetNodeUrns = 1;</code>
     */
    public Builder addAllTargetNodeUrns(
        java.lang.Iterable<java.lang.String> values) {
      ensureTargetNodeUrnsIsMutable();
      super.addAll(values, targetNodeUrns_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string targetNodeUrns = 1;</code>
     */
    public Builder clearTargetNodeUrns() {
      targetNodeUrns_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string targetNodeUrns = 1;</code>
     */
    public Builder addTargetNodeUrnsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureTargetNodeUrnsIsMutable();
      targetNodeUrns_.add(value);
      onChanged();
      return this;
    }

    // required bytes messageBytes = 2;
    private com.google.protobuf.ByteString messageBytes_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>required bytes messageBytes = 2;</code>
     */
    public boolean hasMessageBytes() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes messageBytes = 2;</code>
     */
    public com.google.protobuf.ByteString getMessageBytes() {
      return messageBytes_;
    }
    /**
     * <code>required bytes messageBytes = 2;</code>
     */
    public Builder setMessageBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      messageBytes_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required bytes messageBytes = 2;</code>
     */
    public Builder clearMessageBytes() {
      bitField0_ = (bitField0_ & ~0x00000002);
      messageBytes_ = getDefaultInstance().getMessageBytes();
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessagesRequest)
  }

  static {
    defaultInstance = new SendDownstreamMessagesRequest(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessagesRequest)
}

