// Generated by the protocol buffer compiler.  DO NOT EDIT!

package de.uniluebeck.itm.tr.iwsn.messages;

public  final class SendDownstreamMessagesRequest extends
    com.google.protobuf.GeneratedMessage
    implements SendDownstreamMessagesRequestOrBuilder {
  // Use SendDownstreamMessagesRequest.newBuilder() to construct.
  private SendDownstreamMessagesRequest(Builder builder) {
    super(builder);
  }
  private SendDownstreamMessagesRequest(boolean noInit) {}
  
  private static final SendDownstreamMessagesRequest defaultInstance;
  public static SendDownstreamMessagesRequest getDefaultInstance() {
    return defaultInstance;
  }
  
  public SendDownstreamMessagesRequest getDefaultInstanceForType() {
    return defaultInstance;
  }
  
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return de.uniluebeck.itm.tr.iwsn.messages.Messages.internal_static_de_uniluebeck_itm_tr_iwsn_messages_SendDownstreamMessagesRequest_descriptor;
  }
  
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return de.uniluebeck.itm.tr.iwsn.messages.Messages.internal_static_de_uniluebeck_itm_tr_iwsn_messages_SendDownstreamMessagesRequest_fieldAccessorTable;
  }
  
  private int bitField0_;
  // repeated string targetNodeUrns = 1;
  public static final int TARGETNODEURNS_FIELD_NUMBER = 1;
  private com.google.protobuf.LazyStringList targetNodeUrns_;
  public java.util.List<String>
      getTargetNodeUrnsList() {
    return targetNodeUrns_;
  }
  public int getTargetNodeUrnsCount() {
    return targetNodeUrns_.size();
  }
  public String getTargetNodeUrns(int index) {
    return targetNodeUrns_.get(index);
  }
  
  // required bytes messageBytes = 2;
  public static final int MESSAGEBYTES_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString messageBytes_;
  public boolean hasMessageBytes() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  public com.google.protobuf.ByteString getMessageBytes() {
    return messageBytes_;
  }
  
  private void initFields() {
    targetNodeUrns_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    messageBytes_ = com.google.protobuf.ByteString.EMPTY;
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized != -1) return isInitialized == 1;
    
    if (!hasMessageBytes()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }
  
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    for (int i = 0; i < targetNodeUrns_.size(); i++) {
      output.writeBytes(1, targetNodeUrns_.getByteString(i));
    }
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeBytes(2, messageBytes_);
    }
    getUnknownFields().writeTo(output);
  }
  
  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;
  
    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < targetNodeUrns_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeBytesSizeNoTag(targetNodeUrns_.getByteString(i));
      }
      size += dataSize;
      size += 1 * getTargetNodeUrnsList().size();
    }
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, messageBytes_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }
  
  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }
  
  public static de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessagesRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return newBuilder().mergeFrom(data).buildParsed();
  }
  public static de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessagesRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return newBuilder().mergeFrom(data, extensionRegistry)
             .buildParsed();
  }
  public static de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessagesRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return newBuilder().mergeFrom(data).buildParsed();
  }
  public static de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessagesRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return newBuilder().mergeFrom(data, extensionRegistry)
             .buildParsed();
  }
  public static de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessagesRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return newBuilder().mergeFrom(input).buildParsed();
  }
  public static de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessagesRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return newBuilder().mergeFrom(input, extensionRegistry)
             .buildParsed();
  }
  public static de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessagesRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    Builder builder = newBuilder();
    if (builder.mergeDelimitedFrom(input)) {
      return builder.buildParsed();
    } else {
      return null;
    }
  }
  public static de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessagesRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    Builder builder = newBuilder();
    if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
      return builder.buildParsed();
    } else {
      return null;
    }
  }
  public static de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessagesRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return newBuilder().mergeFrom(input).buildParsed();
  }
  public static de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessagesRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return newBuilder().mergeFrom(input, extensionRegistry)
             .buildParsed();
  }
  
  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessagesRequest prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }
  
  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder>
     implements de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessagesRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.uniluebeck.itm.tr.iwsn.messages.Messages.internal_static_de_uniluebeck_itm_tr_iwsn_messages_SendDownstreamMessagesRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.uniluebeck.itm.tr.iwsn.messages.Messages.internal_static_de_uniluebeck_itm_tr_iwsn_messages_SendDownstreamMessagesRequest_fieldAccessorTable;
    }
    
    // Construct using de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessagesRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }
    
    private Builder(BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    private static Builder create() {
      return new Builder();
    }
    
    public Builder clear() {
      super.clear();
      targetNodeUrns_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      messageBytes_ = com.google.protobuf.ByteString.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }
    
    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }
    
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessagesRequest.getDescriptor();
    }
    
    public de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessagesRequest getDefaultInstanceForType() {
      return de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessagesRequest.getDefaultInstance();
    }
    
    public de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessagesRequest build() {
      de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessagesRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }
    
    private de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessagesRequest buildParsed()
        throws com.google.protobuf.InvalidProtocolBufferException {
      de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessagesRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(
          result).asInvalidProtocolBufferException();
      }
      return result;
    }
    
    public de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessagesRequest buildPartial() {
      de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessagesRequest result = new de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessagesRequest(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        targetNodeUrns_ = new com.google.protobuf.UnmodifiableLazyStringList(
            targetNodeUrns_);
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.targetNodeUrns_ = targetNodeUrns_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000001;
      }
      result.messageBytes_ = messageBytes_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }
    
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessagesRequest) {
        return mergeFrom((de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessagesRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }
    
    public Builder mergeFrom(de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessagesRequest other) {
      if (other == de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessagesRequest.getDefaultInstance()) return this;
      if (!other.targetNodeUrns_.isEmpty()) {
        if (targetNodeUrns_.isEmpty()) {
          targetNodeUrns_ = other.targetNodeUrns_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureTargetNodeUrnsIsMutable();
          targetNodeUrns_.addAll(other.targetNodeUrns_);
        }
        onChanged();
      }
      if (other.hasMessageBytes()) {
        setMessageBytes(other.getMessageBytes());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }
    
    public final boolean isInitialized() {
      if (!hasMessageBytes()) {
        
        return false;
      }
      return true;
    }
    
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder(
          this.getUnknownFields());
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            this.setUnknownFields(unknownFields.build());
            onChanged();
            return this;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            }
            break;
          }
          case 10: {
            ensureTargetNodeUrnsIsMutable();
            targetNodeUrns_.add(input.readBytes());
            break;
          }
          case 18: {
            bitField0_ |= 0x00000002;
            messageBytes_ = input.readBytes();
            break;
          }
        }
      }
    }
    
    private int bitField0_;
    
    // repeated string targetNodeUrns = 1;
    private com.google.protobuf.LazyStringList targetNodeUrns_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureTargetNodeUrnsIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        targetNodeUrns_ = new com.google.protobuf.LazyStringArrayList(targetNodeUrns_);
        bitField0_ |= 0x00000001;
       }
    }
    public java.util.List<String>
        getTargetNodeUrnsList() {
      return java.util.Collections.unmodifiableList(targetNodeUrns_);
    }
    public int getTargetNodeUrnsCount() {
      return targetNodeUrns_.size();
    }
    public String getTargetNodeUrns(int index) {
      return targetNodeUrns_.get(index);
    }
    public Builder setTargetNodeUrns(
        int index, String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureTargetNodeUrnsIsMutable();
      targetNodeUrns_.set(index, value);
      onChanged();
      return this;
    }
    public Builder addTargetNodeUrns(String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureTargetNodeUrnsIsMutable();
      targetNodeUrns_.add(value);
      onChanged();
      return this;
    }
    public Builder addAllTargetNodeUrns(
        java.lang.Iterable<String> values) {
      ensureTargetNodeUrnsIsMutable();
      super.addAll(values, targetNodeUrns_);
      onChanged();
      return this;
    }
    public Builder clearTargetNodeUrns() {
      targetNodeUrns_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    void addTargetNodeUrns(com.google.protobuf.ByteString value) {
      ensureTargetNodeUrnsIsMutable();
      targetNodeUrns_.add(value);
      onChanged();
    }
    
    // required bytes messageBytes = 2;
    private com.google.protobuf.ByteString messageBytes_ = com.google.protobuf.ByteString.EMPTY;
    public boolean hasMessageBytes() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.google.protobuf.ByteString getMessageBytes() {
      return messageBytes_;
    }
    public Builder setMessageBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      messageBytes_ = value;
      onChanged();
      return this;
    }
    public Builder clearMessageBytes() {
      bitField0_ = (bitField0_ & ~0x00000002);
      messageBytes_ = getDefaultInstance().getMessageBytes();
      onChanged();
      return this;
    }
    
    // @@protoc_insertion_point(builder_scope:de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessagesRequest)
  }
  
  static {
    defaultInstance = new SendDownstreamMessagesRequest(true);
    defaultInstance.initFields();
  }
  
  // @@protoc_insertion_point(class_scope:de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessagesRequest)
}

