// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/iwsn-messages.proto

package de.uniluebeck.itm.tr.iwsn.messages;

public interface SetChannelPipelinesRequestOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // repeated string nodeUrns = 1;
  /**
   * <code>repeated string nodeUrns = 1;</code>
   */
  java.util.List<java.lang.String>
  getNodeUrnsList();
  /**
   * <code>repeated string nodeUrns = 1;</code>
   */
  int getNodeUrnsCount();
  /**
   * <code>repeated string nodeUrns = 1;</code>
   */
  java.lang.String getNodeUrns(int index);
  /**
   * <code>repeated string nodeUrns = 1;</code>
   */
  com.google.protobuf.ByteString
      getNodeUrnsBytes(int index);

  // repeated .de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration channelHandlerConfigurations = 2;
  /**
   * <code>repeated .de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration channelHandlerConfigurations = 2;</code>
   */
  java.util.List<de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration> 
      getChannelHandlerConfigurationsList();
  /**
   * <code>repeated .de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration channelHandlerConfigurations = 2;</code>
   */
  de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration getChannelHandlerConfigurations(int index);
  /**
   * <code>repeated .de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration channelHandlerConfigurations = 2;</code>
   */
  int getChannelHandlerConfigurationsCount();
  /**
   * <code>repeated .de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration channelHandlerConfigurations = 2;</code>
   */
  java.util.List<? extends de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfigurationOrBuilder> 
      getChannelHandlerConfigurationsOrBuilderList();
  /**
   * <code>repeated .de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration channelHandlerConfigurations = 2;</code>
   */
  de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfigurationOrBuilder getChannelHandlerConfigurationsOrBuilder(
      int index);
}
