// Generated by the protocol buffer compiler.  DO NOT EDIT!

package de.uniluebeck.itm.tr.iwsn.messages;

public  final class SetChannelPipelinesRequest extends
    com.google.protobuf.GeneratedMessage
    implements SetChannelPipelinesRequestOrBuilder {
  // Use SetChannelPipelinesRequest.newBuilder() to construct.
  private SetChannelPipelinesRequest(Builder builder) {
    super(builder);
  }
  private SetChannelPipelinesRequest(boolean noInit) {}
  
  private static final SetChannelPipelinesRequest defaultInstance;
  public static SetChannelPipelinesRequest getDefaultInstance() {
    return defaultInstance;
  }
  
  public SetChannelPipelinesRequest getDefaultInstanceForType() {
    return defaultInstance;
  }
  
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return de.uniluebeck.itm.tr.iwsn.messages.Messages.internal_static_de_uniluebeck_itm_tr_iwsn_messages_SetChannelPipelinesRequest_descriptor;
  }
  
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return de.uniluebeck.itm.tr.iwsn.messages.Messages.internal_static_de_uniluebeck_itm_tr_iwsn_messages_SetChannelPipelinesRequest_fieldAccessorTable;
  }
  
  private int bitField0_;
  // required .de.uniluebeck.itm.tr.iwsn.messages.Header header = 1;
  public static final int HEADER_FIELD_NUMBER = 1;
  private de.uniluebeck.itm.tr.iwsn.messages.Header header_;
  public boolean hasHeader() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  public de.uniluebeck.itm.tr.iwsn.messages.Header getHeader() {
    return header_;
  }
  public de.uniluebeck.itm.tr.iwsn.messages.HeaderOrBuilder getHeaderOrBuilder() {
    return header_;
  }
  
  // repeated .de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration channelHandlerConfigurations = 2;
  public static final int CHANNELHANDLERCONFIGURATIONS_FIELD_NUMBER = 2;
  private java.util.List<de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration> channelHandlerConfigurations_;
  public java.util.List<de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration> getChannelHandlerConfigurationsList() {
    return channelHandlerConfigurations_;
  }
  public java.util.List<? extends de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfigurationOrBuilder> 
      getChannelHandlerConfigurationsOrBuilderList() {
    return channelHandlerConfigurations_;
  }
  public int getChannelHandlerConfigurationsCount() {
    return channelHandlerConfigurations_.size();
  }
  public de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration getChannelHandlerConfigurations(int index) {
    return channelHandlerConfigurations_.get(index);
  }
  public de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfigurationOrBuilder getChannelHandlerConfigurationsOrBuilder(
      int index) {
    return channelHandlerConfigurations_.get(index);
  }
  
  private void initFields() {
    header_ = de.uniluebeck.itm.tr.iwsn.messages.Header.getDefaultInstance();
    channelHandlerConfigurations_ = java.util.Collections.emptyList();
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized != -1) return isInitialized == 1;
    
    if (!hasHeader()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!getHeader().isInitialized()) {
      memoizedIsInitialized = 0;
      return false;
    }
    for (int i = 0; i < getChannelHandlerConfigurationsCount(); i++) {
      if (!getChannelHandlerConfigurations(i).isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    memoizedIsInitialized = 1;
    return true;
  }
  
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeMessage(1, header_);
    }
    for (int i = 0; i < channelHandlerConfigurations_.size(); i++) {
      output.writeMessage(2, channelHandlerConfigurations_.get(i));
    }
    getUnknownFields().writeTo(output);
  }
  
  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;
  
    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, header_);
    }
    for (int i = 0; i < channelHandlerConfigurations_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, channelHandlerConfigurations_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }
  
  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }
  
  public static de.uniluebeck.itm.tr.iwsn.messages.SetChannelPipelinesRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return newBuilder().mergeFrom(data).buildParsed();
  }
  public static de.uniluebeck.itm.tr.iwsn.messages.SetChannelPipelinesRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return newBuilder().mergeFrom(data, extensionRegistry)
             .buildParsed();
  }
  public static de.uniluebeck.itm.tr.iwsn.messages.SetChannelPipelinesRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return newBuilder().mergeFrom(data).buildParsed();
  }
  public static de.uniluebeck.itm.tr.iwsn.messages.SetChannelPipelinesRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return newBuilder().mergeFrom(data, extensionRegistry)
             .buildParsed();
  }
  public static de.uniluebeck.itm.tr.iwsn.messages.SetChannelPipelinesRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return newBuilder().mergeFrom(input).buildParsed();
  }
  public static de.uniluebeck.itm.tr.iwsn.messages.SetChannelPipelinesRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return newBuilder().mergeFrom(input, extensionRegistry)
             .buildParsed();
  }
  public static de.uniluebeck.itm.tr.iwsn.messages.SetChannelPipelinesRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    Builder builder = newBuilder();
    if (builder.mergeDelimitedFrom(input)) {
      return builder.buildParsed();
    } else {
      return null;
    }
  }
  public static de.uniluebeck.itm.tr.iwsn.messages.SetChannelPipelinesRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    Builder builder = newBuilder();
    if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
      return builder.buildParsed();
    } else {
      return null;
    }
  }
  public static de.uniluebeck.itm.tr.iwsn.messages.SetChannelPipelinesRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return newBuilder().mergeFrom(input).buildParsed();
  }
  public static de.uniluebeck.itm.tr.iwsn.messages.SetChannelPipelinesRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return newBuilder().mergeFrom(input, extensionRegistry)
             .buildParsed();
  }
  
  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(de.uniluebeck.itm.tr.iwsn.messages.SetChannelPipelinesRequest prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }
  
  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder>
     implements de.uniluebeck.itm.tr.iwsn.messages.SetChannelPipelinesRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.uniluebeck.itm.tr.iwsn.messages.Messages.internal_static_de_uniluebeck_itm_tr_iwsn_messages_SetChannelPipelinesRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.uniluebeck.itm.tr.iwsn.messages.Messages.internal_static_de_uniluebeck_itm_tr_iwsn_messages_SetChannelPipelinesRequest_fieldAccessorTable;
    }
    
    // Construct using de.uniluebeck.itm.tr.iwsn.messages.SetChannelPipelinesRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }
    
    private Builder(BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getHeaderFieldBuilder();
        getChannelHandlerConfigurationsFieldBuilder();
      }
    }
    private static Builder create() {
      return new Builder();
    }
    
    public Builder clear() {
      super.clear();
      if (headerBuilder_ == null) {
        header_ = de.uniluebeck.itm.tr.iwsn.messages.Header.getDefaultInstance();
      } else {
        headerBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      if (channelHandlerConfigurationsBuilder_ == null) {
        channelHandlerConfigurations_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        channelHandlerConfigurationsBuilder_.clear();
      }
      return this;
    }
    
    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }
    
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return de.uniluebeck.itm.tr.iwsn.messages.SetChannelPipelinesRequest.getDescriptor();
    }
    
    public de.uniluebeck.itm.tr.iwsn.messages.SetChannelPipelinesRequest getDefaultInstanceForType() {
      return de.uniluebeck.itm.tr.iwsn.messages.SetChannelPipelinesRequest.getDefaultInstance();
    }
    
    public de.uniluebeck.itm.tr.iwsn.messages.SetChannelPipelinesRequest build() {
      de.uniluebeck.itm.tr.iwsn.messages.SetChannelPipelinesRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }
    
    private de.uniluebeck.itm.tr.iwsn.messages.SetChannelPipelinesRequest buildParsed()
        throws com.google.protobuf.InvalidProtocolBufferException {
      de.uniluebeck.itm.tr.iwsn.messages.SetChannelPipelinesRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(
          result).asInvalidProtocolBufferException();
      }
      return result;
    }
    
    public de.uniluebeck.itm.tr.iwsn.messages.SetChannelPipelinesRequest buildPartial() {
      de.uniluebeck.itm.tr.iwsn.messages.SetChannelPipelinesRequest result = new de.uniluebeck.itm.tr.iwsn.messages.SetChannelPipelinesRequest(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      if (headerBuilder_ == null) {
        result.header_ = header_;
      } else {
        result.header_ = headerBuilder_.build();
      }
      if (channelHandlerConfigurationsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          channelHandlerConfigurations_ = java.util.Collections.unmodifiableList(channelHandlerConfigurations_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.channelHandlerConfigurations_ = channelHandlerConfigurations_;
      } else {
        result.channelHandlerConfigurations_ = channelHandlerConfigurationsBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }
    
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof de.uniluebeck.itm.tr.iwsn.messages.SetChannelPipelinesRequest) {
        return mergeFrom((de.uniluebeck.itm.tr.iwsn.messages.SetChannelPipelinesRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }
    
    public Builder mergeFrom(de.uniluebeck.itm.tr.iwsn.messages.SetChannelPipelinesRequest other) {
      if (other == de.uniluebeck.itm.tr.iwsn.messages.SetChannelPipelinesRequest.getDefaultInstance()) return this;
      if (other.hasHeader()) {
        mergeHeader(other.getHeader());
      }
      if (channelHandlerConfigurationsBuilder_ == null) {
        if (!other.channelHandlerConfigurations_.isEmpty()) {
          if (channelHandlerConfigurations_.isEmpty()) {
            channelHandlerConfigurations_ = other.channelHandlerConfigurations_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureChannelHandlerConfigurationsIsMutable();
            channelHandlerConfigurations_.addAll(other.channelHandlerConfigurations_);
          }
          onChanged();
        }
      } else {
        if (!other.channelHandlerConfigurations_.isEmpty()) {
          if (channelHandlerConfigurationsBuilder_.isEmpty()) {
            channelHandlerConfigurationsBuilder_.dispose();
            channelHandlerConfigurationsBuilder_ = null;
            channelHandlerConfigurations_ = other.channelHandlerConfigurations_;
            bitField0_ = (bitField0_ & ~0x00000002);
            channelHandlerConfigurationsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getChannelHandlerConfigurationsFieldBuilder() : null;
          } else {
            channelHandlerConfigurationsBuilder_.addAllMessages(other.channelHandlerConfigurations_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }
    
    public final boolean isInitialized() {
      if (!hasHeader()) {
        
        return false;
      }
      if (!getHeader().isInitialized()) {
        
        return false;
      }
      for (int i = 0; i < getChannelHandlerConfigurationsCount(); i++) {
        if (!getChannelHandlerConfigurations(i).isInitialized()) {
          
          return false;
        }
      }
      return true;
    }
    
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder(
          this.getUnknownFields());
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            this.setUnknownFields(unknownFields.build());
            onChanged();
            return this;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            }
            break;
          }
          case 10: {
            de.uniluebeck.itm.tr.iwsn.messages.Header.Builder subBuilder = de.uniluebeck.itm.tr.iwsn.messages.Header.newBuilder();
            if (hasHeader()) {
              subBuilder.mergeFrom(getHeader());
            }
            input.readMessage(subBuilder, extensionRegistry);
            setHeader(subBuilder.buildPartial());
            break;
          }
          case 18: {
            de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.Builder subBuilder = de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.newBuilder();
            input.readMessage(subBuilder, extensionRegistry);
            addChannelHandlerConfigurations(subBuilder.buildPartial());
            break;
          }
        }
      }
    }
    
    private int bitField0_;
    
    // required .de.uniluebeck.itm.tr.iwsn.messages.Header header = 1;
    private de.uniluebeck.itm.tr.iwsn.messages.Header header_ = de.uniluebeck.itm.tr.iwsn.messages.Header.getDefaultInstance();
    private com.google.protobuf.SingleFieldBuilder<
        de.uniluebeck.itm.tr.iwsn.messages.Header, de.uniluebeck.itm.tr.iwsn.messages.Header.Builder, de.uniluebeck.itm.tr.iwsn.messages.HeaderOrBuilder> headerBuilder_;
    public boolean hasHeader() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public de.uniluebeck.itm.tr.iwsn.messages.Header getHeader() {
      if (headerBuilder_ == null) {
        return header_;
      } else {
        return headerBuilder_.getMessage();
      }
    }
    public Builder setHeader(de.uniluebeck.itm.tr.iwsn.messages.Header value) {
      if (headerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        header_ = value;
        onChanged();
      } else {
        headerBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    public Builder setHeader(
        de.uniluebeck.itm.tr.iwsn.messages.Header.Builder builderForValue) {
      if (headerBuilder_ == null) {
        header_ = builderForValue.build();
        onChanged();
      } else {
        headerBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    public Builder mergeHeader(de.uniluebeck.itm.tr.iwsn.messages.Header value) {
      if (headerBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001) &&
            header_ != de.uniluebeck.itm.tr.iwsn.messages.Header.getDefaultInstance()) {
          header_ =
            de.uniluebeck.itm.tr.iwsn.messages.Header.newBuilder(header_).mergeFrom(value).buildPartial();
        } else {
          header_ = value;
        }
        onChanged();
      } else {
        headerBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    public Builder clearHeader() {
      if (headerBuilder_ == null) {
        header_ = de.uniluebeck.itm.tr.iwsn.messages.Header.getDefaultInstance();
        onChanged();
      } else {
        headerBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }
    public de.uniluebeck.itm.tr.iwsn.messages.Header.Builder getHeaderBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getHeaderFieldBuilder().getBuilder();
    }
    public de.uniluebeck.itm.tr.iwsn.messages.HeaderOrBuilder getHeaderOrBuilder() {
      if (headerBuilder_ != null) {
        return headerBuilder_.getMessageOrBuilder();
      } else {
        return header_;
      }
    }
    private com.google.protobuf.SingleFieldBuilder<
        de.uniluebeck.itm.tr.iwsn.messages.Header, de.uniluebeck.itm.tr.iwsn.messages.Header.Builder, de.uniluebeck.itm.tr.iwsn.messages.HeaderOrBuilder> 
        getHeaderFieldBuilder() {
      if (headerBuilder_ == null) {
        headerBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            de.uniluebeck.itm.tr.iwsn.messages.Header, de.uniluebeck.itm.tr.iwsn.messages.Header.Builder, de.uniluebeck.itm.tr.iwsn.messages.HeaderOrBuilder>(
                header_,
                getParentForChildren(),
                isClean());
        header_ = null;
      }
      return headerBuilder_;
    }
    
    // repeated .de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration channelHandlerConfigurations = 2;
    private java.util.List<de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration> channelHandlerConfigurations_ =
      java.util.Collections.emptyList();
    private void ensureChannelHandlerConfigurationsIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        channelHandlerConfigurations_ = new java.util.ArrayList<de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration>(channelHandlerConfigurations_);
        bitField0_ |= 0x00000002;
       }
    }
    
    private com.google.protobuf.RepeatedFieldBuilder<
        de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration, de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.Builder, de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfigurationOrBuilder> channelHandlerConfigurationsBuilder_;
    
    public java.util.List<de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration> getChannelHandlerConfigurationsList() {
      if (channelHandlerConfigurationsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(channelHandlerConfigurations_);
      } else {
        return channelHandlerConfigurationsBuilder_.getMessageList();
      }
    }
    public int getChannelHandlerConfigurationsCount() {
      if (channelHandlerConfigurationsBuilder_ == null) {
        return channelHandlerConfigurations_.size();
      } else {
        return channelHandlerConfigurationsBuilder_.getCount();
      }
    }
    public de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration getChannelHandlerConfigurations(int index) {
      if (channelHandlerConfigurationsBuilder_ == null) {
        return channelHandlerConfigurations_.get(index);
      } else {
        return channelHandlerConfigurationsBuilder_.getMessage(index);
      }
    }
    public Builder setChannelHandlerConfigurations(
        int index, de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration value) {
      if (channelHandlerConfigurationsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureChannelHandlerConfigurationsIsMutable();
        channelHandlerConfigurations_.set(index, value);
        onChanged();
      } else {
        channelHandlerConfigurationsBuilder_.setMessage(index, value);
      }
      return this;
    }
    public Builder setChannelHandlerConfigurations(
        int index, de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.Builder builderForValue) {
      if (channelHandlerConfigurationsBuilder_ == null) {
        ensureChannelHandlerConfigurationsIsMutable();
        channelHandlerConfigurations_.set(index, builderForValue.build());
        onChanged();
      } else {
        channelHandlerConfigurationsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    public Builder addChannelHandlerConfigurations(de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration value) {
      if (channelHandlerConfigurationsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureChannelHandlerConfigurationsIsMutable();
        channelHandlerConfigurations_.add(value);
        onChanged();
      } else {
        channelHandlerConfigurationsBuilder_.addMessage(value);
      }
      return this;
    }
    public Builder addChannelHandlerConfigurations(
        int index, de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration value) {
      if (channelHandlerConfigurationsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureChannelHandlerConfigurationsIsMutable();
        channelHandlerConfigurations_.add(index, value);
        onChanged();
      } else {
        channelHandlerConfigurationsBuilder_.addMessage(index, value);
      }
      return this;
    }
    public Builder addChannelHandlerConfigurations(
        de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.Builder builderForValue) {
      if (channelHandlerConfigurationsBuilder_ == null) {
        ensureChannelHandlerConfigurationsIsMutable();
        channelHandlerConfigurations_.add(builderForValue.build());
        onChanged();
      } else {
        channelHandlerConfigurationsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    public Builder addChannelHandlerConfigurations(
        int index, de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.Builder builderForValue) {
      if (channelHandlerConfigurationsBuilder_ == null) {
        ensureChannelHandlerConfigurationsIsMutable();
        channelHandlerConfigurations_.add(index, builderForValue.build());
        onChanged();
      } else {
        channelHandlerConfigurationsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    public Builder addAllChannelHandlerConfigurations(
        java.lang.Iterable<? extends de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration> values) {
      if (channelHandlerConfigurationsBuilder_ == null) {
        ensureChannelHandlerConfigurationsIsMutable();
        super.addAll(values, channelHandlerConfigurations_);
        onChanged();
      } else {
        channelHandlerConfigurationsBuilder_.addAllMessages(values);
      }
      return this;
    }
    public Builder clearChannelHandlerConfigurations() {
      if (channelHandlerConfigurationsBuilder_ == null) {
        channelHandlerConfigurations_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        channelHandlerConfigurationsBuilder_.clear();
      }
      return this;
    }
    public Builder removeChannelHandlerConfigurations(int index) {
      if (channelHandlerConfigurationsBuilder_ == null) {
        ensureChannelHandlerConfigurationsIsMutable();
        channelHandlerConfigurations_.remove(index);
        onChanged();
      } else {
        channelHandlerConfigurationsBuilder_.remove(index);
      }
      return this;
    }
    public de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.Builder getChannelHandlerConfigurationsBuilder(
        int index) {
      return getChannelHandlerConfigurationsFieldBuilder().getBuilder(index);
    }
    public de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfigurationOrBuilder getChannelHandlerConfigurationsOrBuilder(
        int index) {
      if (channelHandlerConfigurationsBuilder_ == null) {
        return channelHandlerConfigurations_.get(index);  } else {
        return channelHandlerConfigurationsBuilder_.getMessageOrBuilder(index);
      }
    }
    public java.util.List<? extends de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfigurationOrBuilder> 
         getChannelHandlerConfigurationsOrBuilderList() {
      if (channelHandlerConfigurationsBuilder_ != null) {
        return channelHandlerConfigurationsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(channelHandlerConfigurations_);
      }
    }
    public de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.Builder addChannelHandlerConfigurationsBuilder() {
      return getChannelHandlerConfigurationsFieldBuilder().addBuilder(
          de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.getDefaultInstance());
    }
    public de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.Builder addChannelHandlerConfigurationsBuilder(
        int index) {
      return getChannelHandlerConfigurationsFieldBuilder().addBuilder(
          index, de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.getDefaultInstance());
    }
    public java.util.List<de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.Builder> 
         getChannelHandlerConfigurationsBuilderList() {
      return getChannelHandlerConfigurationsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration, de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.Builder, de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfigurationOrBuilder> 
        getChannelHandlerConfigurationsFieldBuilder() {
      if (channelHandlerConfigurationsBuilder_ == null) {
        channelHandlerConfigurationsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration, de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfiguration.Builder, de.uniluebeck.itm.tr.iwsn.messages.ChannelHandlerConfigurationOrBuilder>(
                channelHandlerConfigurations_,
                ((bitField0_ & 0x00000002) == 0x00000002),
                getParentForChildren(),
                isClean());
        channelHandlerConfigurations_ = null;
      }
      return channelHandlerConfigurationsBuilder_;
    }
    
    // @@protoc_insertion_point(builder_scope:de.uniluebeck.itm.tr.iwsn.messages.SetChannelPipelinesRequest)
  }
  
  static {
    defaultInstance = new SetChannelPipelinesRequest(true);
    defaultInstance.initFields();
  }
  
  // @@protoc_insertion_point(class_scope:de.uniluebeck.itm.tr.iwsn.messages.SetChannelPipelinesRequest)
}

