// Generated by the protocol buffer compiler.  DO NOT EDIT!

package de.uniluebeck.itm.tr.iwsn.messages;

public interface SetChannelPipelinesRequestOrBuilder
    extends com.google.protobuf.MessageOrBuilder {
  
  // repeated string nodeUrns = 1;
  java.util.List<String> getNodeUrnsList();
  int getNodeUrnsCount();
  String getNodeUrns(int index);
  
  // repeated .de.uniluebeck.itm.tr.iwsn.messages.SetChannelPipelinesRequest.ChannelHandlerConfiguration channelHandlerConfigurations = 2;
  java.util.List<de.uniluebeck.itm.tr.iwsn.messages.SetChannelPipelinesRequest.ChannelHandlerConfiguration> 
      getChannelHandlerConfigurationsList();
  de.uniluebeck.itm.tr.iwsn.messages.SetChannelPipelinesRequest.ChannelHandlerConfiguration getChannelHandlerConfigurations(int index);
  int getChannelHandlerConfigurationsCount();
  java.util.List<? extends de.uniluebeck.itm.tr.iwsn.messages.SetChannelPipelinesRequest.ChannelHandlerConfigurationOrBuilder> 
      getChannelHandlerConfigurationsOrBuilderList();
  de.uniluebeck.itm.tr.iwsn.messages.SetChannelPipelinesRequest.ChannelHandlerConfigurationOrBuilder getChannelHandlerConfigurationsOrBuilder(
      int index);
}
