delete from ConfidentialReservationDataInternal;
delete from ConfidentialReservationDataInternal_Users;
delete from PublicReservationDataInternal;
delete from ReservationDataInternal;
delete from SecretReservationKeyInternal;
delete from Users;
delete from reservationdata_urns;
