package de.uniluebeck.itm.tr.snaa.shiro.entity;
// Generated 13.11.2012 17:06:11 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Action generated by hbm2java
 */
@Entity
@Table(name="ACTIONS"
    ,catalog="trauth"
)
public class Action  implements java.io.Serializable {


     private String name;
     private Set<Permission> permissions = new HashSet<Permission>(0);

    public Action() {
    }

	
    public Action(String name) {
        this.name = name;
    }
    public Action(String name, Set<Permission> permissions) {
       this.name = name;
       this.permissions = permissions;
    }
   
     @Id 
    
    @Column(name="NAME", unique=true, nullable=false, length=30)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="action")
    public Set<Permission> getPermissions() {
        return this.permissions;
    }
    
    public void setPermissions(Set<Permission> permissions) {
        this.permissions = permissions;
    }




}


