package de.uniluebeck.itm.tr.snaa.shiro.entity;
// Generated 13.11.2012 17:06:11 by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Permission generated by hbm2java
 */
@Entity
@Table(name="PERMISSIONS"
    ,catalog="trauth"
)
public class Permission  implements java.io.Serializable {


     private PermissionId id;
     private Action action;
     private ResourceGroup resourceGroup;
     private Role role;

    public Permission() {
    }

	
    public Permission(PermissionId id, Action action, Role role) {
        this.id = id;
        this.action = action;
        this.role = role;
    }
    public Permission(PermissionId id, Action action, ResourceGroup resourceGroup, Role role) {
       this.id = id;
       this.action = action;
       this.resourceGroup = resourceGroup;
       this.role = role;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="roleName", column=@Column(name="ROLE_NAME", nullable=false, length=150) ), 
        @AttributeOverride(name="actionName", column=@Column(name="ACTION_NAME", nullable=false, length=30) ), 
        @AttributeOverride(name="resourcegroupName", column=@Column(name="RESOURCEGROUP_NAME", length=40) ) } )
    public PermissionId getId() {
        return this.id;
    }
    
    public void setId(PermissionId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ACTION_NAME", nullable=false, insertable=false, updatable=false)
    public Action getAction() {
        return this.action;
    }
    
    public void setAction(Action action) {
        this.action = action;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="RESOURCEGROUP_NAME", insertable=false, updatable=false)
    public ResourceGroup getResourceGroup() {
        return this.resourceGroup;
    }
    
    public void setResourceGroup(ResourceGroup resourceGroup) {
        this.resourceGroup = resourceGroup;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ROLE_NAME", nullable=false, insertable=false, updatable=false)
    public Role getRole() {
        return this.role;
    }
    
    public void setRole(Role role) {
        this.role = role;
    }




}


