#!/bin/bash

PORTAL_USER=root
PORTAL_HOST=staging.wisebed.itm.uni-luebeck.de
PORTAL_CONFIGS[0]=tr.iwsn-portal.properties
PORTAL_CONFIGS[1]=tr.iwsn-portal-snaa-jpa.properties
PORTAL_CONFIGS[2]=tr.iwsn-portal-rs-jpa.properties
PORTAL_CONFIGS[3]=tr.iwsn-portal-devicedb-jpa.properties

FEDERATOR_USER=root
FEDERATOR_HOST=staging.wisebed.itm.uni-luebeck.de
FEDERATOR_CONFIGS[0]=tr.federator.properties

GATEWAY_USER=root
GATEWAY_HOSTS[0]=testbeduzl22.wisebed.itm.uni-luebeck.de
GATEWAY_HOSTS[1]=testbeduzl35.wisebed.itm.uni-luebeck.de
GATEWAY_CONFIGS[0]=tr.iwsn-gateway.properties
GATEWAY_CONFIGS[1]=tr.iwsn-gateway.log4j.properties
