#!/bin/bash

PORTAL_USER=root
PORTAL_HOST=testbeduzl22.wisebed.itm.uni-luebeck.de

FEDERATOR_USER=root
FEDERATOR_HOST=testbeduzl22.wisebed.itm.uni-luebeck.de

GATEWAY_USER=root
GATEWAY_HOSTS[0]=testbeduzl22.wisebed.itm.uni-luebeck.de
GATEWAY_HOSTS[1]=testbeduzl35.wisebed.itm.uni-luebeck.de
