<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="urn:MessageStore"
			 xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://schemas.xmlsoap.org/wsdl/"
			 targetNamespace="urn:MessageStore" name="MessageStore">

	<types>
		<xsd:schema>
			<xsd:import namespace="urn:WSNService" schemaLocation="WSNServiceTypes.xsd" />
		</xsd:schema>
		<xsd:schema>
			<xsd:import namespace="urn:MessageStore" schemaLocation="MessageStoreTypes.xsd" />
		</xsd:schema>
		<xsd:schema>
			<xsd:import namespace="urn:CommonTypes" schemaLocation="CommonTypes.xsd" />
		</xsd:schema>
	</types>

	<message name="hasMessages">
		<part name="parameters" element="tns:hasMessages" />
	</message>
	<message name="hasMessagesResponse">
		<part name="parameters" element="tns:hasMessagesResponse" />
	</message>
	<message name="fetchMessages">
		<part name="parameters" element="tns:fetchMessages" />
	</message>
	<message name="fetchMessagesResponse">
		<part name="parameters" element="tns:fetchMessagesResponse" />
	</message>

	<portType name="MessageStore">
		<operation name="hasMessages">
			<input message="tns:hasMessages" />
			<output message="tns:hasMessagesResponse" />
		</operation>
		<operation name="fetchMessages">
			<input message="tns:fetchMessages" />
			<output message="tns:fetchMessagesResponse" />
		</operation>
	</portType>

	<binding name="MessageStorePortBinding" type="tns:MessageStore">
		<soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document" />
		<operation name="hasMessages">
			<soap:operation soapAction="" />
			<input>
				<soap:body use="literal" />
			</input>
			<output>
				<soap:body use="literal" />
			</output>
		</operation>
		<operation name="fetchMessages">
			<soap:operation soapAction="" />
			<input>
				<soap:body use="literal" />
			</input>
			<output>
				<soap:body use="literal" />
			</output>
		</operation>
	</binding>

	<service name="MessageStore">
		<port name="MessageStorePort" binding="tns:MessageStorePortBinding">
			<soap:address location="REPLACE_WITH_ACTUAL_URL" />
		</port>
	</service>

</definitions>