//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.14 at 01:47:45 PM MEZ 
//


package de.uniluebeck.itm.tr.xml;

import java.util.ArrayList;
import java.util.List;
import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NodeNames complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NodeNames">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="nodename" type="{http://itm.uniluebeck.de/tr/xml}NodeName" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NodeNames", propOrder = {
    "nodename"
})
@Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2011-11-14T01:47:45+01:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
public class NodeNames {

    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2011-11-14T01:47:45+01:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    protected List<NodeName> nodename;

    /**
     * Gets the value of the nodename property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nodename property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNodename().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NodeName }
     * 
     * 
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2011-11-14T01:47:45+01:00", comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
    public List<NodeName> getNodename() {
        if (nodename == null) {
            nodename = new ArrayList<NodeName>();
        }
        return this.nodename;
    }

}
