//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.06.03 at 09:15:54 AM MESZ 
//


package eu.wisebed.ns.wiseml._1;

import javax.annotation.Generated;
import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for timeinfo complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="timeinfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://wisebed.eu/ns/wiseml/1.0}start"/>
 *         &lt;choice>
 *           &lt;element ref="{http://wisebed.eu/ns/wiseml/1.0}end"/>
 *           &lt;element ref="{http://wisebed.eu/ns/wiseml/1.0}duration"/>
 *         &lt;/choice>
 *         &lt;element ref="{http://wisebed.eu/ns/wiseml/1.0}unit"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "timeinfo", propOrder = {
		"start",
		"end",
		"duration",
		"unit"
})
@Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2010-06-03T09:15:54+02:00",
		comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
public class Timeinfo {

	@XmlElement(required = true)
	@XmlSchemaType(name = "dateTime")
	@Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2010-06-03T09:15:54+02:00",
			comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
	protected XMLGregorianCalendar start;

	@XmlSchemaType(name = "dateTime")
	@Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2010-06-03T09:15:54+02:00",
			comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
	protected XMLGregorianCalendar end;

	@Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2010-06-03T09:15:54+02:00",
			comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
	protected String duration;

	@XmlElement(required = true)
	@Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2010-06-03T09:15:54+02:00",
			comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
	protected String unit;

	/**
	 * Gets the value of the start property.
	 *
	 * @return possible object is {@link XMLGregorianCalendar }
	 */
	@Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2010-06-03T09:15:54+02:00",
			comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
	public XMLGregorianCalendar getStart() {
		return start;
	}

	/**
	 * Sets the value of the start property.
	 *
	 * @param value allowed object is {@link XMLGregorianCalendar }
	 */
	@Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2010-06-03T09:15:54+02:00",
			comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
	public void setStart(XMLGregorianCalendar value) {
		this.start = value;
	}

	/**
	 * Gets the value of the end property.
	 *
	 * @return possible object is {@link XMLGregorianCalendar }
	 */
	@Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2010-06-03T09:15:54+02:00",
			comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
	public XMLGregorianCalendar getEnd() {
		return end;
	}

	/**
	 * Sets the value of the end property.
	 *
	 * @param value allowed object is {@link XMLGregorianCalendar }
	 */
	@Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2010-06-03T09:15:54+02:00",
			comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
	public void setEnd(XMLGregorianCalendar value) {
		this.end = value;
	}

	/**
	 * Gets the value of the duration property.
	 *
	 * @return possible object is {@link String }
	 */
	@Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2010-06-03T09:15:54+02:00",
			comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
	public String getDuration() {
		return duration;
	}

	/**
	 * Sets the value of the duration property.
	 *
	 * @param value allowed object is {@link String }
	 */
	@Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2010-06-03T09:15:54+02:00",
			comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
	public void setDuration(String value) {
		this.duration = value;
	}

	/**
	 * Gets the value of the unit property.
	 *
	 * @return possible object is {@link String }
	 */
	@Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2010-06-03T09:15:54+02:00",
			comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
	public String getUnit() {
		return unit;
	}

	/**
	 * Sets the value of the unit property.
	 *
	 * @param value allowed object is {@link String }
	 */
	@Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2010-06-03T09:15:54+02:00",
			comments = "JAXB RI vJAXB 2.1.10 in JDK 6")
	public void setUnit(String value) {
		this.unit = value;
	}

}
