// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/overlay-messages.proto

package de.uniluebeck.itm.tr.iwsn.overlay.messaging;

public final class Messages {
  private Messages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class Msg extends
      com.google.protobuf.GeneratedMessage {
    // Use Msg.newBuilder() to construct.
    private Msg() {
      initFields();
    }
    private Msg(boolean noInit) {}
    
    private static final Msg defaultInstance;
    public static Msg getDefaultInstance() {
      return defaultInstance;
    }
    
    public Msg getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.internal_static_de_uniluebeck_itm_tr_iwsn_overlay_messaging_Msg_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.internal_static_de_uniluebeck_itm_tr_iwsn_overlay_messaging_Msg_fieldAccessorTable;
    }
    
    // required string to = 1;
    public static final int TO_FIELD_NUMBER = 1;
    private boolean hasTo;
    private java.lang.String to_ = "";
    public boolean hasTo() { return hasTo; }
    public java.lang.String getTo() { return to_; }
    
    // required string from = 2;
    public static final int FROM_FIELD_NUMBER = 2;
    private boolean hasFrom;
    private java.lang.String from_ = "";
    public boolean hasFrom() { return hasFrom; }
    public java.lang.String getFrom() { return from_; }
    
    // required string msgType = 3;
    public static final int MSGTYPE_FIELD_NUMBER = 3;
    private boolean hasMsgType;
    private java.lang.String msgType_ = "";
    public boolean hasMsgType() { return hasMsgType; }
    public java.lang.String getMsgType() { return msgType_; }
    
    // required uint32 priority = 4;
    public static final int PRIORITY_FIELD_NUMBER = 4;
    private boolean hasPriority;
    private int priority_ = 0;
    public boolean hasPriority() { return hasPriority; }
    public int getPriority() { return priority_; }
    
    // optional bytes payload = 5;
    public static final int PAYLOAD_FIELD_NUMBER = 5;
    private boolean hasPayload;
    private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
    public boolean hasPayload() { return hasPayload; }
    public com.google.protobuf.ByteString getPayload() { return payload_; }
    
    // optional string replyWith = 6;
    public static final int REPLYWITH_FIELD_NUMBER = 6;
    private boolean hasReplyWith;
    private java.lang.String replyWith_ = "";
    public boolean hasReplyWith() { return hasReplyWith; }
    public java.lang.String getReplyWith() { return replyWith_; }
    
    // optional string replyTo = 7;
    public static final int REPLYTO_FIELD_NUMBER = 7;
    private boolean hasReplyTo;
    private java.lang.String replyTo_ = "";
    public boolean hasReplyTo() { return hasReplyTo; }
    public java.lang.String getReplyTo() { return replyTo_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasTo) return false;
      if (!hasFrom) return false;
      if (!hasMsgType) return false;
      if (!hasPriority) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasTo()) {
        output.writeString(1, getTo());
      }
      if (hasFrom()) {
        output.writeString(2, getFrom());
      }
      if (hasMsgType()) {
        output.writeString(3, getMsgType());
      }
      if (hasPriority()) {
        output.writeUInt32(4, getPriority());
      }
      if (hasPayload()) {
        output.writeBytes(5, getPayload());
      }
      if (hasReplyWith()) {
        output.writeString(6, getReplyWith());
      }
      if (hasReplyTo()) {
        output.writeString(7, getReplyTo());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasTo()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getTo());
      }
      if (hasFrom()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getFrom());
      }
      if (hasMsgType()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getMsgType());
      }
      if (hasPriority()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, getPriority());
      }
      if (hasPayload()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getPayload());
      }
      if (hasReplyWith()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(6, getReplyWith());
      }
      if (hasReplyTo()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(7, getReplyTo());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.Msg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.Msg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.Msg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.Msg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.Msg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.Msg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.Msg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.Msg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.Msg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.Msg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.Msg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.Msg result;
      
      // Construct using de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.Msg.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.Msg();
        return builder;
      }
      
      protected de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.Msg internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.Msg();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.Msg.getDescriptor();
      }
      
      public de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.Msg getDefaultInstanceForType() {
        return de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.Msg.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.Msg build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.Msg buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.Msg buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.Msg returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.Msg) {
          return mergeFrom((de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.Msg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.Msg other) {
        if (other == de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.Msg.getDefaultInstance()) return this;
        if (other.hasTo()) {
          setTo(other.getTo());
        }
        if (other.hasFrom()) {
          setFrom(other.getFrom());
        }
        if (other.hasMsgType()) {
          setMsgType(other.getMsgType());
        }
        if (other.hasPriority()) {
          setPriority(other.getPriority());
        }
        if (other.hasPayload()) {
          setPayload(other.getPayload());
        }
        if (other.hasReplyWith()) {
          setReplyWith(other.getReplyWith());
        }
        if (other.hasReplyTo()) {
          setReplyTo(other.getReplyTo());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setTo(input.readString());
              break;
            }
            case 18: {
              setFrom(input.readString());
              break;
            }
            case 26: {
              setMsgType(input.readString());
              break;
            }
            case 32: {
              setPriority(input.readUInt32());
              break;
            }
            case 42: {
              setPayload(input.readBytes());
              break;
            }
            case 50: {
              setReplyWith(input.readString());
              break;
            }
            case 58: {
              setReplyTo(input.readString());
              break;
            }
          }
        }
      }
      
      
      // required string to = 1;
      public boolean hasTo() {
        return result.hasTo();
      }
      public java.lang.String getTo() {
        return result.getTo();
      }
      public Builder setTo(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasTo = true;
        result.to_ = value;
        return this;
      }
      public Builder clearTo() {
        result.hasTo = false;
        result.to_ = getDefaultInstance().getTo();
        return this;
      }
      
      // required string from = 2;
      public boolean hasFrom() {
        return result.hasFrom();
      }
      public java.lang.String getFrom() {
        return result.getFrom();
      }
      public Builder setFrom(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasFrom = true;
        result.from_ = value;
        return this;
      }
      public Builder clearFrom() {
        result.hasFrom = false;
        result.from_ = getDefaultInstance().getFrom();
        return this;
      }
      
      // required string msgType = 3;
      public boolean hasMsgType() {
        return result.hasMsgType();
      }
      public java.lang.String getMsgType() {
        return result.getMsgType();
      }
      public Builder setMsgType(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasMsgType = true;
        result.msgType_ = value;
        return this;
      }
      public Builder clearMsgType() {
        result.hasMsgType = false;
        result.msgType_ = getDefaultInstance().getMsgType();
        return this;
      }
      
      // required uint32 priority = 4;
      public boolean hasPriority() {
        return result.hasPriority();
      }
      public int getPriority() {
        return result.getPriority();
      }
      public Builder setPriority(int value) {
        result.hasPriority = true;
        result.priority_ = value;
        return this;
      }
      public Builder clearPriority() {
        result.hasPriority = false;
        result.priority_ = 0;
        return this;
      }
      
      // optional bytes payload = 5;
      public boolean hasPayload() {
        return result.hasPayload();
      }
      public com.google.protobuf.ByteString getPayload() {
        return result.getPayload();
      }
      public Builder setPayload(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasPayload = true;
        result.payload_ = value;
        return this;
      }
      public Builder clearPayload() {
        result.hasPayload = false;
        result.payload_ = getDefaultInstance().getPayload();
        return this;
      }
      
      // optional string replyWith = 6;
      public boolean hasReplyWith() {
        return result.hasReplyWith();
      }
      public java.lang.String getReplyWith() {
        return result.getReplyWith();
      }
      public Builder setReplyWith(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasReplyWith = true;
        result.replyWith_ = value;
        return this;
      }
      public Builder clearReplyWith() {
        result.hasReplyWith = false;
        result.replyWith_ = getDefaultInstance().getReplyWith();
        return this;
      }
      
      // optional string replyTo = 7;
      public boolean hasReplyTo() {
        return result.hasReplyTo();
      }
      public java.lang.String getReplyTo() {
        return result.getReplyTo();
      }
      public Builder setReplyTo(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasReplyTo = true;
        result.replyTo_ = value;
        return this;
      }
      public Builder clearReplyTo() {
        result.hasReplyTo = false;
        result.replyTo_ = getDefaultInstance().getReplyTo();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:de.uniluebeck.itm.tr.iwsn.overlay.messaging.Msg)
    }
    
    static {
      defaultInstance = new Msg(true);
      de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:de.uniluebeck.itm.tr.iwsn.overlay.messaging.Msg)
  }
  
  public static final class SingleRequestMultipleResponseRequest extends
      com.google.protobuf.GeneratedMessage {
    // Use SingleRequestMultipleResponseRequest.newBuilder() to construct.
    private SingleRequestMultipleResponseRequest() {
      initFields();
    }
    private SingleRequestMultipleResponseRequest(boolean noInit) {}
    
    private static final SingleRequestMultipleResponseRequest defaultInstance;
    public static SingleRequestMultipleResponseRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public SingleRequestMultipleResponseRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.internal_static_de_uniluebeck_itm_tr_iwsn_overlay_messaging_SingleRequestMultipleResponseRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.internal_static_de_uniluebeck_itm_tr_iwsn_overlay_messaging_SingleRequestMultipleResponseRequest_fieldAccessorTable;
    }
    
    // required string requestId = 1;
    public static final int REQUESTID_FIELD_NUMBER = 1;
    private boolean hasRequestId;
    private java.lang.String requestId_ = "";
    public boolean hasRequestId() { return hasRequestId; }
    public java.lang.String getRequestId() { return requestId_; }
    
    // required bytes payload = 2;
    public static final int PAYLOAD_FIELD_NUMBER = 2;
    private boolean hasPayload;
    private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
    public boolean hasPayload() { return hasPayload; }
    public com.google.protobuf.ByteString getPayload() { return payload_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasRequestId) return false;
      if (!hasPayload) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasRequestId()) {
        output.writeString(1, getRequestId());
      }
      if (hasPayload()) {
        output.writeBytes(2, getPayload());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasRequestId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getRequestId());
      }
      if (hasPayload()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getPayload());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseRequest result;
      
      // Construct using de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseRequest.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseRequest();
        return builder;
      }
      
      protected de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseRequest internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseRequest();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseRequest.getDescriptor();
      }
      
      public de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseRequest getDefaultInstanceForType() {
        return de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseRequest.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseRequest build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseRequest buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseRequest returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseRequest) {
          return mergeFrom((de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseRequest other) {
        if (other == de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseRequest.getDefaultInstance()) return this;
        if (other.hasRequestId()) {
          setRequestId(other.getRequestId());
        }
        if (other.hasPayload()) {
          setPayload(other.getPayload());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setRequestId(input.readString());
              break;
            }
            case 18: {
              setPayload(input.readBytes());
              break;
            }
          }
        }
      }
      
      
      // required string requestId = 1;
      public boolean hasRequestId() {
        return result.hasRequestId();
      }
      public java.lang.String getRequestId() {
        return result.getRequestId();
      }
      public Builder setRequestId(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasRequestId = true;
        result.requestId_ = value;
        return this;
      }
      public Builder clearRequestId() {
        result.hasRequestId = false;
        result.requestId_ = getDefaultInstance().getRequestId();
        return this;
      }
      
      // required bytes payload = 2;
      public boolean hasPayload() {
        return result.hasPayload();
      }
      public com.google.protobuf.ByteString getPayload() {
        return result.getPayload();
      }
      public Builder setPayload(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasPayload = true;
        result.payload_ = value;
        return this;
      }
      public Builder clearPayload() {
        result.hasPayload = false;
        result.payload_ = getDefaultInstance().getPayload();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:de.uniluebeck.itm.tr.iwsn.overlay.messaging.SingleRequestMultipleResponseRequest)
    }
    
    static {
      defaultInstance = new SingleRequestMultipleResponseRequest(true);
      de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:de.uniluebeck.itm.tr.iwsn.overlay.messaging.SingleRequestMultipleResponseRequest)
  }
  
  public static final class SingleRequestMultipleResponseResponse extends
      com.google.protobuf.GeneratedMessage {
    // Use SingleRequestMultipleResponseResponse.newBuilder() to construct.
    private SingleRequestMultipleResponseResponse() {
      initFields();
    }
    private SingleRequestMultipleResponseResponse(boolean noInit) {}
    
    private static final SingleRequestMultipleResponseResponse defaultInstance;
    public static SingleRequestMultipleResponseResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public SingleRequestMultipleResponseResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.internal_static_de_uniluebeck_itm_tr_iwsn_overlay_messaging_SingleRequestMultipleResponseResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.internal_static_de_uniluebeck_itm_tr_iwsn_overlay_messaging_SingleRequestMultipleResponseResponse_fieldAccessorTable;
    }
    
    // required string requestId = 1;
    public static final int REQUESTID_FIELD_NUMBER = 1;
    private boolean hasRequestId;
    private java.lang.String requestId_ = "";
    public boolean hasRequestId() { return hasRequestId; }
    public java.lang.String getRequestId() { return requestId_; }
    
    // required bytes payload = 2;
    public static final int PAYLOAD_FIELD_NUMBER = 2;
    private boolean hasPayload;
    private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
    public boolean hasPayload() { return hasPayload; }
    public com.google.protobuf.ByteString getPayload() { return payload_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasRequestId) return false;
      if (!hasPayload) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasRequestId()) {
        output.writeString(1, getRequestId());
      }
      if (hasPayload()) {
        output.writeBytes(2, getPayload());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasRequestId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getRequestId());
      }
      if (hasPayload()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getPayload());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseResponse result;
      
      // Construct using de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseResponse.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseResponse();
        return builder;
      }
      
      protected de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseResponse internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseResponse();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseResponse.getDescriptor();
      }
      
      public de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseResponse getDefaultInstanceForType() {
        return de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseResponse.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseResponse build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseResponse buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseResponse returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseResponse) {
          return mergeFrom((de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseResponse other) {
        if (other == de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseResponse.getDefaultInstance()) return this;
        if (other.hasRequestId()) {
          setRequestId(other.getRequestId());
        }
        if (other.hasPayload()) {
          setPayload(other.getPayload());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setRequestId(input.readString());
              break;
            }
            case 18: {
              setPayload(input.readBytes());
              break;
            }
          }
        }
      }
      
      
      // required string requestId = 1;
      public boolean hasRequestId() {
        return result.hasRequestId();
      }
      public java.lang.String getRequestId() {
        return result.getRequestId();
      }
      public Builder setRequestId(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasRequestId = true;
        result.requestId_ = value;
        return this;
      }
      public Builder clearRequestId() {
        result.hasRequestId = false;
        result.requestId_ = getDefaultInstance().getRequestId();
        return this;
      }
      
      // required bytes payload = 2;
      public boolean hasPayload() {
        return result.hasPayload();
      }
      public com.google.protobuf.ByteString getPayload() {
        return result.getPayload();
      }
      public Builder setPayload(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasPayload = true;
        result.payload_ = value;
        return this;
      }
      public Builder clearPayload() {
        result.hasPayload = false;
        result.payload_ = getDefaultInstance().getPayload();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:de.uniluebeck.itm.tr.iwsn.overlay.messaging.SingleRequestMultipleResponseResponse)
    }
    
    static {
      defaultInstance = new SingleRequestMultipleResponseResponse(true);
      de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:de.uniluebeck.itm.tr.iwsn.overlay.messaging.SingleRequestMultipleResponseResponse)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_de_uniluebeck_itm_tr_iwsn_overlay_messaging_Msg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_de_uniluebeck_itm_tr_iwsn_overlay_messaging_Msg_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_de_uniluebeck_itm_tr_iwsn_overlay_messaging_SingleRequestMultipleResponseRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_de_uniluebeck_itm_tr_iwsn_overlay_messaging_SingleRequestMultipleResponseRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_de_uniluebeck_itm_tr_iwsn_overlay_messaging_SingleRequestMultipleResponseResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_de_uniluebeck_itm_tr_iwsn_overlay_messaging_SingleRequestMultipleResponseResponse_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n)src/main/resources/overlay-messages.pr" +
      "oto\022+de.uniluebeck.itm.tr.iwsn.overlay.m" +
      "essaging\"w\n\003Msg\022\n\n\002to\030\001 \002(\t\022\014\n\004from\030\002 \002(" +
      "\t\022\017\n\007msgType\030\003 \002(\t\022\020\n\010priority\030\004 \002(\r\022\017\n\007" +
      "payload\030\005 \001(\014\022\021\n\treplyWith\030\006 \001(\t\022\017\n\007repl" +
      "yTo\030\007 \001(\t\"J\n$SingleRequestMultipleRespon" +
      "seRequest\022\021\n\trequestId\030\001 \002(\t\022\017\n\007payload\030" +
      "\002 \002(\014\"K\n%SingleRequestMultipleResponseRe" +
      "sponse\022\021\n\trequestId\030\001 \002(\t\022\017\n\007payload\030\002 \002" +
      "(\014B\nB\010Messages"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_de_uniluebeck_itm_tr_iwsn_overlay_messaging_Msg_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_de_uniluebeck_itm_tr_iwsn_overlay_messaging_Msg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_de_uniluebeck_itm_tr_iwsn_overlay_messaging_Msg_descriptor,
              new java.lang.String[] { "To", "From", "MsgType", "Priority", "Payload", "ReplyWith", "ReplyTo", },
              de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.Msg.class,
              de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.Msg.Builder.class);
          internal_static_de_uniluebeck_itm_tr_iwsn_overlay_messaging_SingleRequestMultipleResponseRequest_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_de_uniluebeck_itm_tr_iwsn_overlay_messaging_SingleRequestMultipleResponseRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_de_uniluebeck_itm_tr_iwsn_overlay_messaging_SingleRequestMultipleResponseRequest_descriptor,
              new java.lang.String[] { "RequestId", "Payload", },
              de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseRequest.class,
              de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseRequest.Builder.class);
          internal_static_de_uniluebeck_itm_tr_iwsn_overlay_messaging_SingleRequestMultipleResponseResponse_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_de_uniluebeck_itm_tr_iwsn_overlay_messaging_SingleRequestMultipleResponseResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_de_uniluebeck_itm_tr_iwsn_overlay_messaging_SingleRequestMultipleResponseResponse_descriptor,
              new java.lang.String[] { "RequestId", "Payload", },
              de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseResponse.class,
              de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseResponse.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
