// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/overlay-messages.proto

package de.uniluebeck.itm.tr.iwsn.overlay.messaging;

public final class Messages {
  private Messages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string to = 1;
    boolean hasTo();
    String getTo();
    
    // required string from = 2;
    boolean hasFrom();
    String getFrom();
    
    // required string msgType = 3;
    boolean hasMsgType();
    String getMsgType();
    
    // required uint32 priority = 4;
    boolean hasPriority();
    int getPriority();
    
    // optional bytes payload = 5;
    boolean hasPayload();
    com.google.protobuf.ByteString getPayload();
    
    // optional string replyWith = 6;
    boolean hasReplyWith();
    String getReplyWith();
    
    // optional string replyTo = 7;
    boolean hasReplyTo();
    String getReplyTo();
  }
  public static final class Msg extends
      com.google.protobuf.GeneratedMessage
      implements MsgOrBuilder {
    // Use Msg.newBuilder() to construct.
    private Msg(Builder builder) {
      super(builder);
    }
    private Msg(boolean noInit) {}
    
    private static final Msg defaultInstance;
    public static Msg getDefaultInstance() {
      return defaultInstance;
    }
    
    public Msg getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.internal_static_de_uniluebeck_itm_tr_iwsn_overlay_messaging_Msg_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.internal_static_de_uniluebeck_itm_tr_iwsn_overlay_messaging_Msg_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string to = 1;
    public static final int TO_FIELD_NUMBER = 1;
    private java.lang.Object to_;
    public boolean hasTo() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getTo() {
      java.lang.Object ref = to_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          to_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getToBytes() {
      java.lang.Object ref = to_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        to_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string from = 2;
    public static final int FROM_FIELD_NUMBER = 2;
    private java.lang.Object from_;
    public boolean hasFrom() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getFrom() {
      java.lang.Object ref = from_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          from_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getFromBytes() {
      java.lang.Object ref = from_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        from_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string msgType = 3;
    public static final int MSGTYPE_FIELD_NUMBER = 3;
    private java.lang.Object msgType_;
    public boolean hasMsgType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getMsgType() {
      java.lang.Object ref = msgType_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          msgType_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getMsgTypeBytes() {
      java.lang.Object ref = msgType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        msgType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required uint32 priority = 4;
    public static final int PRIORITY_FIELD_NUMBER = 4;
    private int priority_;
    public boolean hasPriority() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getPriority() {
      return priority_;
    }
    
    // optional bytes payload = 5;
    public static final int PAYLOAD_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString payload_;
    public boolean hasPayload() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public com.google.protobuf.ByteString getPayload() {
      return payload_;
    }
    
    // optional string replyWith = 6;
    public static final int REPLYWITH_FIELD_NUMBER = 6;
    private java.lang.Object replyWith_;
    public boolean hasReplyWith() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public String getReplyWith() {
      java.lang.Object ref = replyWith_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          replyWith_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getReplyWithBytes() {
      java.lang.Object ref = replyWith_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        replyWith_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string replyTo = 7;
    public static final int REPLYTO_FIELD_NUMBER = 7;
    private java.lang.Object replyTo_;
    public boolean hasReplyTo() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public String getReplyTo() {
      java.lang.Object ref = replyTo_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          replyTo_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getReplyToBytes() {
      java.lang.Object ref = replyTo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        replyTo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      to_ = "";
      from_ = "";
      msgType_ = "";
      priority_ = 0;
      payload_ = com.google.protobuf.ByteString.EMPTY;
      replyWith_ = "";
      replyTo_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasTo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFrom()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMsgType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPriority()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getToBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getFromBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getMsgTypeBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt32(4, priority_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, payload_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getReplyWithBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getReplyToBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getToBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getFromBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getMsgTypeBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, priority_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, payload_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getReplyWithBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getReplyToBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.Msg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.Msg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.Msg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.Msg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.Msg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.Msg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.Msg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.Msg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.Msg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.Msg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.Msg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.MsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.internal_static_de_uniluebeck_itm_tr_iwsn_overlay_messaging_Msg_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.internal_static_de_uniluebeck_itm_tr_iwsn_overlay_messaging_Msg_fieldAccessorTable;
      }
      
      // Construct using de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.Msg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        to_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        from_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        msgType_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        priority_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        payload_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        replyWith_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        replyTo_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.Msg.getDescriptor();
      }
      
      public de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.Msg getDefaultInstanceForType() {
        return de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.Msg.getDefaultInstance();
      }
      
      public de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.Msg build() {
        de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.Msg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.Msg buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.Msg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.Msg buildPartial() {
        de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.Msg result = new de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.Msg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.to_ = to_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.from_ = from_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.msgType_ = msgType_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.priority_ = priority_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.payload_ = payload_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.replyWith_ = replyWith_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.replyTo_ = replyTo_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.Msg) {
          return mergeFrom((de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.Msg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.Msg other) {
        if (other == de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.Msg.getDefaultInstance()) return this;
        if (other.hasTo()) {
          setTo(other.getTo());
        }
        if (other.hasFrom()) {
          setFrom(other.getFrom());
        }
        if (other.hasMsgType()) {
          setMsgType(other.getMsgType());
        }
        if (other.hasPriority()) {
          setPriority(other.getPriority());
        }
        if (other.hasPayload()) {
          setPayload(other.getPayload());
        }
        if (other.hasReplyWith()) {
          setReplyWith(other.getReplyWith());
        }
        if (other.hasReplyTo()) {
          setReplyTo(other.getReplyTo());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasTo()) {
          
          return false;
        }
        if (!hasFrom()) {
          
          return false;
        }
        if (!hasMsgType()) {
          
          return false;
        }
        if (!hasPriority()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              to_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              from_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              msgType_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              priority_ = input.readUInt32();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              payload_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              replyWith_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              replyTo_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string to = 1;
      private java.lang.Object to_ = "";
      public boolean hasTo() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getTo() {
        java.lang.Object ref = to_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          to_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTo(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        to_ = value;
        onChanged();
        return this;
      }
      public Builder clearTo() {
        bitField0_ = (bitField0_ & ~0x00000001);
        to_ = getDefaultInstance().getTo();
        onChanged();
        return this;
      }
      void setTo(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        to_ = value;
        onChanged();
      }
      
      // required string from = 2;
      private java.lang.Object from_ = "";
      public boolean hasFrom() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getFrom() {
        java.lang.Object ref = from_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          from_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setFrom(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        from_ = value;
        onChanged();
        return this;
      }
      public Builder clearFrom() {
        bitField0_ = (bitField0_ & ~0x00000002);
        from_ = getDefaultInstance().getFrom();
        onChanged();
        return this;
      }
      void setFrom(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        from_ = value;
        onChanged();
      }
      
      // required string msgType = 3;
      private java.lang.Object msgType_ = "";
      public boolean hasMsgType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getMsgType() {
        java.lang.Object ref = msgType_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          msgType_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setMsgType(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        msgType_ = value;
        onChanged();
        return this;
      }
      public Builder clearMsgType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        msgType_ = getDefaultInstance().getMsgType();
        onChanged();
        return this;
      }
      void setMsgType(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        msgType_ = value;
        onChanged();
      }
      
      // required uint32 priority = 4;
      private int priority_ ;
      public boolean hasPriority() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getPriority() {
        return priority_;
      }
      public Builder setPriority(int value) {
        bitField0_ |= 0x00000008;
        priority_ = value;
        onChanged();
        return this;
      }
      public Builder clearPriority() {
        bitField0_ = (bitField0_ & ~0x00000008);
        priority_ = 0;
        onChanged();
        return this;
      }
      
      // optional bytes payload = 5;
      private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasPayload() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public com.google.protobuf.ByteString getPayload() {
        return payload_;
      }
      public Builder setPayload(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        payload_ = value;
        onChanged();
        return this;
      }
      public Builder clearPayload() {
        bitField0_ = (bitField0_ & ~0x00000010);
        payload_ = getDefaultInstance().getPayload();
        onChanged();
        return this;
      }
      
      // optional string replyWith = 6;
      private java.lang.Object replyWith_ = "";
      public boolean hasReplyWith() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public String getReplyWith() {
        java.lang.Object ref = replyWith_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          replyWith_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setReplyWith(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        replyWith_ = value;
        onChanged();
        return this;
      }
      public Builder clearReplyWith() {
        bitField0_ = (bitField0_ & ~0x00000020);
        replyWith_ = getDefaultInstance().getReplyWith();
        onChanged();
        return this;
      }
      void setReplyWith(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000020;
        replyWith_ = value;
        onChanged();
      }
      
      // optional string replyTo = 7;
      private java.lang.Object replyTo_ = "";
      public boolean hasReplyTo() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public String getReplyTo() {
        java.lang.Object ref = replyTo_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          replyTo_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setReplyTo(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        replyTo_ = value;
        onChanged();
        return this;
      }
      public Builder clearReplyTo() {
        bitField0_ = (bitField0_ & ~0x00000040);
        replyTo_ = getDefaultInstance().getReplyTo();
        onChanged();
        return this;
      }
      void setReplyTo(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000040;
        replyTo_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:de.uniluebeck.itm.tr.iwsn.overlay.messaging.Msg)
    }
    
    static {
      defaultInstance = new Msg(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:de.uniluebeck.itm.tr.iwsn.overlay.messaging.Msg)
  }
  
  public interface SingleRequestMultipleResponseRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string requestId = 1;
    boolean hasRequestId();
    String getRequestId();
    
    // required bytes payload = 2;
    boolean hasPayload();
    com.google.protobuf.ByteString getPayload();
  }
  public static final class SingleRequestMultipleResponseRequest extends
      com.google.protobuf.GeneratedMessage
      implements SingleRequestMultipleResponseRequestOrBuilder {
    // Use SingleRequestMultipleResponseRequest.newBuilder() to construct.
    private SingleRequestMultipleResponseRequest(Builder builder) {
      super(builder);
    }
    private SingleRequestMultipleResponseRequest(boolean noInit) {}
    
    private static final SingleRequestMultipleResponseRequest defaultInstance;
    public static SingleRequestMultipleResponseRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public SingleRequestMultipleResponseRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.internal_static_de_uniluebeck_itm_tr_iwsn_overlay_messaging_SingleRequestMultipleResponseRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.internal_static_de_uniluebeck_itm_tr_iwsn_overlay_messaging_SingleRequestMultipleResponseRequest_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string requestId = 1;
    public static final int REQUESTID_FIELD_NUMBER = 1;
    private java.lang.Object requestId_;
    public boolean hasRequestId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getRequestId() {
      java.lang.Object ref = requestId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          requestId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getRequestIdBytes() {
      java.lang.Object ref = requestId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        requestId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required bytes payload = 2;
    public static final int PAYLOAD_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString payload_;
    public boolean hasPayload() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.google.protobuf.ByteString getPayload() {
      return payload_;
    }
    
    private void initFields() {
      requestId_ = "";
      payload_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasRequestId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPayload()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getRequestIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, payload_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getRequestIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, payload_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.internal_static_de_uniluebeck_itm_tr_iwsn_overlay_messaging_SingleRequestMultipleResponseRequest_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.internal_static_de_uniluebeck_itm_tr_iwsn_overlay_messaging_SingleRequestMultipleResponseRequest_fieldAccessorTable;
      }
      
      // Construct using de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        requestId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        payload_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseRequest.getDescriptor();
      }
      
      public de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseRequest getDefaultInstanceForType() {
        return de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseRequest.getDefaultInstance();
      }
      
      public de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseRequest build() {
        de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseRequest buildPartial() {
        de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseRequest result = new de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.requestId_ = requestId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.payload_ = payload_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseRequest) {
          return mergeFrom((de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseRequest other) {
        if (other == de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseRequest.getDefaultInstance()) return this;
        if (other.hasRequestId()) {
          setRequestId(other.getRequestId());
        }
        if (other.hasPayload()) {
          setPayload(other.getPayload());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasRequestId()) {
          
          return false;
        }
        if (!hasPayload()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              requestId_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              payload_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string requestId = 1;
      private java.lang.Object requestId_ = "";
      public boolean hasRequestId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getRequestId() {
        java.lang.Object ref = requestId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          requestId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setRequestId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        requestId_ = value;
        onChanged();
        return this;
      }
      public Builder clearRequestId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        requestId_ = getDefaultInstance().getRequestId();
        onChanged();
        return this;
      }
      void setRequestId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        requestId_ = value;
        onChanged();
      }
      
      // required bytes payload = 2;
      private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasPayload() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.google.protobuf.ByteString getPayload() {
        return payload_;
      }
      public Builder setPayload(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        payload_ = value;
        onChanged();
        return this;
      }
      public Builder clearPayload() {
        bitField0_ = (bitField0_ & ~0x00000002);
        payload_ = getDefaultInstance().getPayload();
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:de.uniluebeck.itm.tr.iwsn.overlay.messaging.SingleRequestMultipleResponseRequest)
    }
    
    static {
      defaultInstance = new SingleRequestMultipleResponseRequest(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:de.uniluebeck.itm.tr.iwsn.overlay.messaging.SingleRequestMultipleResponseRequest)
  }
  
  public interface SingleRequestMultipleResponseResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string requestId = 1;
    boolean hasRequestId();
    String getRequestId();
    
    // required bytes payload = 2;
    boolean hasPayload();
    com.google.protobuf.ByteString getPayload();
  }
  public static final class SingleRequestMultipleResponseResponse extends
      com.google.protobuf.GeneratedMessage
      implements SingleRequestMultipleResponseResponseOrBuilder {
    // Use SingleRequestMultipleResponseResponse.newBuilder() to construct.
    private SingleRequestMultipleResponseResponse(Builder builder) {
      super(builder);
    }
    private SingleRequestMultipleResponseResponse(boolean noInit) {}
    
    private static final SingleRequestMultipleResponseResponse defaultInstance;
    public static SingleRequestMultipleResponseResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public SingleRequestMultipleResponseResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.internal_static_de_uniluebeck_itm_tr_iwsn_overlay_messaging_SingleRequestMultipleResponseResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.internal_static_de_uniluebeck_itm_tr_iwsn_overlay_messaging_SingleRequestMultipleResponseResponse_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string requestId = 1;
    public static final int REQUESTID_FIELD_NUMBER = 1;
    private java.lang.Object requestId_;
    public boolean hasRequestId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getRequestId() {
      java.lang.Object ref = requestId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          requestId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getRequestIdBytes() {
      java.lang.Object ref = requestId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        requestId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required bytes payload = 2;
    public static final int PAYLOAD_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString payload_;
    public boolean hasPayload() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.google.protobuf.ByteString getPayload() {
      return payload_;
    }
    
    private void initFields() {
      requestId_ = "";
      payload_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasRequestId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPayload()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getRequestIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, payload_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getRequestIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, payload_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.internal_static_de_uniluebeck_itm_tr_iwsn_overlay_messaging_SingleRequestMultipleResponseResponse_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.internal_static_de_uniluebeck_itm_tr_iwsn_overlay_messaging_SingleRequestMultipleResponseResponse_fieldAccessorTable;
      }
      
      // Construct using de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        requestId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        payload_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseResponse.getDescriptor();
      }
      
      public de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseResponse getDefaultInstanceForType() {
        return de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseResponse.getDefaultInstance();
      }
      
      public de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseResponse build() {
        de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseResponse buildPartial() {
        de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseResponse result = new de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.requestId_ = requestId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.payload_ = payload_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseResponse) {
          return mergeFrom((de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseResponse other) {
        if (other == de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseResponse.getDefaultInstance()) return this;
        if (other.hasRequestId()) {
          setRequestId(other.getRequestId());
        }
        if (other.hasPayload()) {
          setPayload(other.getPayload());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasRequestId()) {
          
          return false;
        }
        if (!hasPayload()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              requestId_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              payload_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string requestId = 1;
      private java.lang.Object requestId_ = "";
      public boolean hasRequestId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getRequestId() {
        java.lang.Object ref = requestId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          requestId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setRequestId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        requestId_ = value;
        onChanged();
        return this;
      }
      public Builder clearRequestId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        requestId_ = getDefaultInstance().getRequestId();
        onChanged();
        return this;
      }
      void setRequestId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        requestId_ = value;
        onChanged();
      }
      
      // required bytes payload = 2;
      private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasPayload() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.google.protobuf.ByteString getPayload() {
        return payload_;
      }
      public Builder setPayload(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        payload_ = value;
        onChanged();
        return this;
      }
      public Builder clearPayload() {
        bitField0_ = (bitField0_ & ~0x00000002);
        payload_ = getDefaultInstance().getPayload();
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:de.uniluebeck.itm.tr.iwsn.overlay.messaging.SingleRequestMultipleResponseResponse)
    }
    
    static {
      defaultInstance = new SingleRequestMultipleResponseResponse(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:de.uniluebeck.itm.tr.iwsn.overlay.messaging.SingleRequestMultipleResponseResponse)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_de_uniluebeck_itm_tr_iwsn_overlay_messaging_Msg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_de_uniluebeck_itm_tr_iwsn_overlay_messaging_Msg_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_de_uniluebeck_itm_tr_iwsn_overlay_messaging_SingleRequestMultipleResponseRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_de_uniluebeck_itm_tr_iwsn_overlay_messaging_SingleRequestMultipleResponseRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_de_uniluebeck_itm_tr_iwsn_overlay_messaging_SingleRequestMultipleResponseResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_de_uniluebeck_itm_tr_iwsn_overlay_messaging_SingleRequestMultipleResponseResponse_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n)src/main/resources/overlay-messages.pr" +
      "oto\022+de.uniluebeck.itm.tr.iwsn.overlay.m" +
      "essaging\"w\n\003Msg\022\n\n\002to\030\001 \002(\t\022\014\n\004from\030\002 \002(" +
      "\t\022\017\n\007msgType\030\003 \002(\t\022\020\n\010priority\030\004 \002(\r\022\017\n\007" +
      "payload\030\005 \001(\014\022\021\n\treplyWith\030\006 \001(\t\022\017\n\007repl" +
      "yTo\030\007 \001(\t\"J\n$SingleRequestMultipleRespon" +
      "seRequest\022\021\n\trequestId\030\001 \002(\t\022\017\n\007payload\030" +
      "\002 \002(\014\"K\n%SingleRequestMultipleResponseRe" +
      "sponse\022\021\n\trequestId\030\001 \002(\t\022\017\n\007payload\030\002 \002" +
      "(\014B\nB\010Messages"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_de_uniluebeck_itm_tr_iwsn_overlay_messaging_Msg_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_de_uniluebeck_itm_tr_iwsn_overlay_messaging_Msg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_de_uniluebeck_itm_tr_iwsn_overlay_messaging_Msg_descriptor,
              new java.lang.String[] { "To", "From", "MsgType", "Priority", "Payload", "ReplyWith", "ReplyTo", },
              de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.Msg.class,
              de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.Msg.Builder.class);
          internal_static_de_uniluebeck_itm_tr_iwsn_overlay_messaging_SingleRequestMultipleResponseRequest_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_de_uniluebeck_itm_tr_iwsn_overlay_messaging_SingleRequestMultipleResponseRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_de_uniluebeck_itm_tr_iwsn_overlay_messaging_SingleRequestMultipleResponseRequest_descriptor,
              new java.lang.String[] { "RequestId", "Payload", },
              de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseRequest.class,
              de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseRequest.Builder.class);
          internal_static_de_uniluebeck_itm_tr_iwsn_overlay_messaging_SingleRequestMultipleResponseResponse_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_de_uniluebeck_itm_tr_iwsn_overlay_messaging_SingleRequestMultipleResponseResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_de_uniluebeck_itm_tr_iwsn_overlay_messaging_SingleRequestMultipleResponseResponse_descriptor,
              new java.lang.String[] { "RequestId", "Payload", },
              de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseResponse.class,
              de.uniluebeck.itm.tr.iwsn.overlay.messaging.Messages.SingleRequestMultipleResponseResponse.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
