package de.uniluebeck.itm.tr.snaa.shiro.entity;
// Generated 26 juil. 2013 14:38:11 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UsersCert generated by hbm2java
 */
@Entity
@Table(name="USERS_CERT"
    ,catalog="trauth"
)
public class UsersCert  implements java.io.Serializable {


     private String name;
     private Organization organization;
     private boolean hascertificate;
     private Set<Role> roles = new HashSet<Role>(0);

    public UsersCert() {
    }

	
    public UsersCert(String name, Organization organization, boolean hascertificate) {
        this.name = name;
        this.organization = organization;
        this.hascertificate = hascertificate;
    }
    public UsersCert(String name, Organization organization, boolean hascertificate, Set<Role> roles) {
       this.name = name;
       this.organization = organization;
       this.hascertificate = hascertificate;
       this.roles = roles;
    }
   
     @Id 
    
    @Column(name="NAME", unique=true, nullable=false, length=150)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ORGANIZATIONID", nullable=false)
    public Organization getOrganization() {
        return this.organization;
    }
    
    public void setOrganization(Organization organization) {
        this.organization = organization;
    }
    
    @Column(name="HASCERTIFICATE", nullable=false)
    public boolean isHascertificate() {
        return this.hascertificate;
    }
    
    public void setHascertificate(boolean hascertificate) {
        this.hascertificate = hascertificate;
    }
@ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY)
    @JoinTable(name="USERSCERT_ROLES", catalog="trauth", joinColumns = { 
        @JoinColumn(name="USERSCERT_NAME", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="ROLE_NAME", nullable=false, updatable=false) })
    public Set<Role> getRoles() {
        return this.roles;
    }
    
    public void setRoles(Set<Role> roles) {
        this.roles = roles;
    }




}


