#!/bin/bash
curl -v -X POST -d @src/test/resources/device-0x2037.json -H Content-Type:application/json http://localhost:7654/rest/deviceConfigs && echo
curl -v -X POST -d @src/test/resources/device-0x2038.json -H Content-Type:application/json http://localhost:7654/rest/deviceConfigs && echo
