// Generated by the protocol buffer compiler.  DO NOT EDIT!

package de.uniluebeck.itm.tr.iwsn.messages;

public  final class SendDownstreamMessageRequest extends
    com.google.protobuf.GeneratedMessage {
  // Use SendDownstreamMessageRequest.newBuilder() to construct.
  private SendDownstreamMessageRequest() {
    initFields();
  }
  private SendDownstreamMessageRequest(boolean noInit) {}
  
  private static final SendDownstreamMessageRequest defaultInstance;
  public static SendDownstreamMessageRequest getDefaultInstance() {
    return defaultInstance;
  }
  
  public SendDownstreamMessageRequest getDefaultInstanceForType() {
    return defaultInstance;
  }
  
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return de.uniluebeck.itm.tr.iwsn.messages.Messages.internal_static_de_uniluebeck_itm_tr_iwsn_messages_SendDownstreamMessageRequest_descriptor;
  }
  
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return de.uniluebeck.itm.tr.iwsn.messages.Messages.internal_static_de_uniluebeck_itm_tr_iwsn_messages_SendDownstreamMessageRequest_fieldAccessorTable;
  }
  
  // repeated string targetNodeUrns = 1;
  public static final int TARGETNODEURNS_FIELD_NUMBER = 1;
  private java.util.List<java.lang.String> targetNodeUrns_ =
    java.util.Collections.emptyList();
  public java.util.List<java.lang.String> getTargetNodeUrnsList() {
    return targetNodeUrns_;
  }
  public int getTargetNodeUrnsCount() { return targetNodeUrns_.size(); }
  public java.lang.String getTargetNodeUrns(int index) {
    return targetNodeUrns_.get(index);
  }
  
  // required bytes messageBytes = 2;
  public static final int MESSAGEBYTES_FIELD_NUMBER = 2;
  private boolean hasMessageBytes;
  private com.google.protobuf.ByteString messageBytes_ = com.google.protobuf.ByteString.EMPTY;
  public boolean hasMessageBytes() { return hasMessageBytes; }
  public com.google.protobuf.ByteString getMessageBytes() { return messageBytes_; }
  
  private void initFields() {
  }
  public final boolean isInitialized() {
    if (!hasMessageBytes) return false;
    return true;
  }
  
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    for (java.lang.String element : getTargetNodeUrnsList()) {
      output.writeString(1, element);
    }
    if (hasMessageBytes()) {
      output.writeBytes(2, getMessageBytes());
    }
    getUnknownFields().writeTo(output);
  }
  
  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;
  
    size = 0;
    {
      int dataSize = 0;
      for (java.lang.String element : getTargetNodeUrnsList()) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeStringSizeNoTag(element);
      }
      size += dataSize;
      size += 1 * getTargetNodeUrnsList().size();
    }
    if (hasMessageBytes()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, getMessageBytes());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }
  
  public static de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessageRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return newBuilder().mergeFrom(data).buildParsed();
  }
  public static de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessageRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return newBuilder().mergeFrom(data, extensionRegistry)
             .buildParsed();
  }
  public static de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessageRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return newBuilder().mergeFrom(data).buildParsed();
  }
  public static de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessageRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return newBuilder().mergeFrom(data, extensionRegistry)
             .buildParsed();
  }
  public static de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessageRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return newBuilder().mergeFrom(input).buildParsed();
  }
  public static de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessageRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return newBuilder().mergeFrom(input, extensionRegistry)
             .buildParsed();
  }
  public static de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessageRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    Builder builder = newBuilder();
    if (builder.mergeDelimitedFrom(input)) {
      return builder.buildParsed();
    } else {
      return null;
    }
  }
  public static de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessageRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    Builder builder = newBuilder();
    if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
      return builder.buildParsed();
    } else {
      return null;
    }
  }
  public static de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessageRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return newBuilder().mergeFrom(input).buildParsed();
  }
  public static de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessageRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return newBuilder().mergeFrom(input, extensionRegistry)
             .buildParsed();
  }
  
  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessageRequest prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }
  
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> {
    private de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessageRequest result;
    
    // Construct using de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessageRequest.newBuilder()
    private Builder() {}
    
    private static Builder create() {
      Builder builder = new Builder();
      builder.result = new de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessageRequest();
      return builder;
    }
    
    protected de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessageRequest internalGetResult() {
      return result;
    }
    
    public Builder clear() {
      if (result == null) {
        throw new IllegalStateException(
          "Cannot call clear() after build().");
      }
      result = new de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessageRequest();
      return this;
    }
    
    public Builder clone() {
      return create().mergeFrom(result);
    }
    
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessageRequest.getDescriptor();
    }
    
    public de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessageRequest getDefaultInstanceForType() {
      return de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessageRequest.getDefaultInstance();
    }
    
    public boolean isInitialized() {
      return result.isInitialized();
    }
    public de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessageRequest build() {
      if (result != null && !isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return buildPartial();
    }
    
    private de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessageRequest buildParsed()
        throws com.google.protobuf.InvalidProtocolBufferException {
      if (!isInitialized()) {
        throw newUninitializedMessageException(
          result).asInvalidProtocolBufferException();
      }
      return buildPartial();
    }
    
    public de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessageRequest buildPartial() {
      if (result == null) {
        throw new IllegalStateException(
          "build() has already been called on this Builder.");
      }
      if (result.targetNodeUrns_ != java.util.Collections.EMPTY_LIST) {
        result.targetNodeUrns_ =
          java.util.Collections.unmodifiableList(result.targetNodeUrns_);
      }
      de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessageRequest returnMe = result;
      result = null;
      return returnMe;
    }
    
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessageRequest) {
        return mergeFrom((de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessageRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }
    
    public Builder mergeFrom(de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessageRequest other) {
      if (other == de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessageRequest.getDefaultInstance()) return this;
      if (!other.targetNodeUrns_.isEmpty()) {
        if (result.targetNodeUrns_.isEmpty()) {
          result.targetNodeUrns_ = new java.util.ArrayList<java.lang.String>();
        }
        result.targetNodeUrns_.addAll(other.targetNodeUrns_);
      }
      if (other.hasMessageBytes()) {
        setMessageBytes(other.getMessageBytes());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }
    
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder(
          this.getUnknownFields());
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            this.setUnknownFields(unknownFields.build());
            return this;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              this.setUnknownFields(unknownFields.build());
              return this;
            }
            break;
          }
          case 10: {
            addTargetNodeUrns(input.readString());
            break;
          }
          case 18: {
            setMessageBytes(input.readBytes());
            break;
          }
        }
      }
    }
    
    
    // repeated string targetNodeUrns = 1;
    public java.util.List<java.lang.String> getTargetNodeUrnsList() {
      return java.util.Collections.unmodifiableList(result.targetNodeUrns_);
    }
    public int getTargetNodeUrnsCount() {
      return result.getTargetNodeUrnsCount();
    }
    public java.lang.String getTargetNodeUrns(int index) {
      return result.getTargetNodeUrns(index);
    }
    public Builder setTargetNodeUrns(int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  result.targetNodeUrns_.set(index, value);
      return this;
    }
    public Builder addTargetNodeUrns(java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  if (result.targetNodeUrns_.isEmpty()) {
        result.targetNodeUrns_ = new java.util.ArrayList<java.lang.String>();
      }
      result.targetNodeUrns_.add(value);
      return this;
    }
    public Builder addAllTargetNodeUrns(
        java.lang.Iterable<? extends java.lang.String> values) {
      if (result.targetNodeUrns_.isEmpty()) {
        result.targetNodeUrns_ = new java.util.ArrayList<java.lang.String>();
      }
      super.addAll(values, result.targetNodeUrns_);
      return this;
    }
    public Builder clearTargetNodeUrns() {
      result.targetNodeUrns_ = java.util.Collections.emptyList();
      return this;
    }
    
    // required bytes messageBytes = 2;
    public boolean hasMessageBytes() {
      return result.hasMessageBytes();
    }
    public com.google.protobuf.ByteString getMessageBytes() {
      return result.getMessageBytes();
    }
    public Builder setMessageBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  result.hasMessageBytes = true;
      result.messageBytes_ = value;
      return this;
    }
    public Builder clearMessageBytes() {
      result.hasMessageBytes = false;
      result.messageBytes_ = getDefaultInstance().getMessageBytes();
      return this;
    }
    
    // @@protoc_insertion_point(builder_scope:de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessageRequest)
  }
  
  static {
    defaultInstance = new SendDownstreamMessageRequest(true);
    de.uniluebeck.itm.tr.iwsn.messages.Messages.internalForceInit();
    defaultInstance.initFields();
  }
  
  // @@protoc_insertion_point(class_scope:de.uniluebeck.itm.tr.iwsn.messages.SendDownstreamMessageRequest)
}

